In [ ]:
!pip install nfl_data_py --no-deps
!pip install appdirs

Collecting nfl_data_py
  Using cached nfl_data_py-0.3.3-py3-none-any.whl.metadata (12 kB)
Downloading nfl_data_py-0.3.3-py3-none-any.whl (13 kB)
Installing collected packages: nfl_data_py
Successfully installed nfl_data_py-0.3.3
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: appdirs
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nfl-data-py 0.3.3 requires fastparquet>0.5, which is not installed.
nfl-data-py 0.3.3 requires numpy<2.0,>=1.0, but you have numpy 2.0.2 which is incompatible.
nfl-data-py 0.3.3 requires pandas<2.0,>=1.0, but you have pandas 2.2.2 which is incompatible.
Successfully installed appdirs-1.4.4

In [ ]:
!pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2026.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.0.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 25.7 MB/s eta 0:00:00
Installing collected packages: fastparquet
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nfl-data-py 0.3.3 requires numpy<2.0,>=1.0, but you have numpy 2.0.2 which is incompatible.
nfl-data-py 0.3.3 requires pandas<2.0,>=1.0, but you have pandas 2.2.2 which is incompatible.
Successfully installed fastparquet-2026.5.0

In [ ]:
import nfl_data_py as nfl

data = nfl.import_seasonal_data([2023, 2024, 2025])

data.head()

HTTPError: HTTP Error 404: Not Found

In [ ]:
import nfl_data_py as nfl

data = nfl.import_seasonal_data([2023])

data.head()

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0023459,2023,REG,0,1,0.0,0,0.0,1.0,10.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,00-0024243,2023,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.069712,0.057342,0.027384,0.125,0.036364,0.047619,0.076192,0.046907,0.197279,0.028467
2,00-0026158,2023,REG,123,204,1616.0,13,8.0,8.0,57.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.191464
3,00-0026498,2023,REG,326,521,3965.0,24,11.0,30.0,205.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.173299
4,00-0026625,2023,REG,23,42,231.0,0,2.0,1.0,8.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036106

In [ ]:
data_2024 = nfl.import_seasonal_data([2024])
data_2024.head()

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0023459,2024,REG,368,584,3897.0,28,11.0,40.0,302.0,...,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.177032
1,00-0024243,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.006757,0.059271,0.00885,0.0,0.071429,0.055556,0.004425,0.00708,0.068966,0.010541
2,00-0026158,2024,REG,162,248,1761.0,12,7.0,18.0,123.0,...,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.156155
3,00-0026300,2024,REG,2,3,17.0,0,0.0,1.0,5.0,...,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.001842
4,00-0026498,2024,REG,340,517,3762.0,20,8.0,28.0,213.0,...,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.164457

In [ ]:
data_2025 = nfl.import_seasonal_data([2025])
data_2025.head()

HTTPError: HTTP Error 404: Not Found

In [ ]:
!pip install nflreadpy

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.32.4)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (1.35.2)
Requirement already satisfied: platformdirs>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.10.0)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.67.3)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.13.4)
Collecting pydantic-settings>=2.0.0 (from nflreadpy)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->nflreadpy) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2026.6.17)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.9 MB/s eta 0:00:00
Installing collected packages: pydantic-settings, nflreadpy
Successfully installed nflreadpy-0.1.5 pydantic-settings-2.14.2

In [ ]:
import nflreadpy as nfl

data = nfl.load_player_stats([2023, 2024, 2025])

data.head()

shape: (5, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002649 ┆ M.Staffor ┆ Matthew   ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 14.46     ┆ 14.46     │
│ 8         ┆ d         ┆ Stafford  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# keep only the columns we actually care about
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]

fantasy_data = data.select(fantasy_cols)

fantasy_data.head()

shape: (5, 18)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Aaron       ┆ QB       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Rodgers     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Matt Prater ┆ K        ┆ ARI  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Nick Folk   ┆ K        ┆ TEN  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Calais      ┆ DE       ┆ ATL  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Campbell    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Matthew     ┆ QB       ┆ LA   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 14.46      ┆ 14.46      │
│ Stafford    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# only keep the fantasy-relevant positions
fantasy_data = fantasy_data.filter(
    fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])
)

fantasy_data.head()

shape: (5, 18)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Aaron       ┆ QB       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Rodgers     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Matthew     ┆ QB       ┆ LA   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 14.46      ┆ 14.46      │
│ Stafford    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Randall     ┆ WR       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Cobb        ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tyrod       ┆ QB       ┆ NYG  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.24       ┆ 0.24       │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Brandon     ┆ RB       ┆ LV   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Bolden      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# add up each player's stats across the whole season
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("completions").sum(),
        pl.col("attempts").sum(),
        pl.col("passing_yards").sum(),
        pl.col("passing_tds").sum(),
        pl.col("passing_interceptions").sum(),
        pl.col("carries").sum(),
        pl.col("rushing_yards").sum(),
        pl.col("rushing_tds").sum(),
        pl.col("receptions").sum(),
        pl.col("receiving_yards").sum(),
        pl.col("receiving_tds").sum(),
        pl.col("fantasy_points").sum(),
        pl.col("fantasy_points_ppr").sum(),
    ]
)

season_totals.head()

NameError: name 'pl' is not defined

In [ ]:
import polars as pl

season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("completions").sum(),
        pl.col("attempts").sum(),
        pl.col("passing_yards").sum(),
        pl.col("passing_tds").sum(),
        pl.col("passing_interceptions").sum(),
        pl.col("carries").sum(),
        pl.col("rushing_yards").sum(),
        pl.col("rushing_tds").sum(),
        pl.col("receptions").sum(),
        pl.col("receiving_yards").sum(),
        pl.col("receiving_tds").sum(),
        pl.col("fantasy_points").sum(),
        pl.col("fantasy_points_ppr").sum(),
    ]
)

season_totals.head()

shape: (5, 17)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Brayden     ┆ TE       ┆ SF   ┆ 2025   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Willis      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ameer       ┆ RB       ┆ LV   ┆ 2023   ┆ … ┆ 131         ┆ 0           ┆ 22.0       ┆ 41.0       │
│ Abdullah    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Irvin       ┆ WR       ┆ NYJ  ┆ 2024   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Charles     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jauan       ┆ WR       ┆ SF   ┆ 2024   ┆ … ┆ 975         ┆ 6           ┆ 133.5      ┆ 210.5      │
│ Jennings    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tim Jones   ┆ WR       ┆ JAX  ┆ 2023   ┆ … ┆ 83          ┆ 0           ┆ 8.3        ┆ 19.3       │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# sort by PPR fantasy points, highest first, for the most recent season
top_players_2025 = season_totals.filter(pl.col("season") == 2025).sort(
    "fantasy_points_ppr", descending=True
)

top_players_2025.head(20)

shape: (20, 17)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 1029        ┆ 9           ┆ 345.4      ┆ 458.4      │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Puka Nacua  ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 2047        ┆ 12          ┆ 299.6      ┆ 452.6      │
│ Drake Maye  ┆ QB       ┆ NE   ┆ 2025   ┆ … ┆ 2           ┆ 0           ┆ 415.88     ┆ 416.88     │
│ Josh Allen  ┆ QB       ┆ BUF  ┆ 2025   ┆ … ┆ 0           ┆ 0           ┆ 416.76     ┆ 416.76     │
│ Matthew     ┆ QB       ┆ LA   ┆ 2025   ┆ … ┆ 0           ┆ 0           ┆ 411.32     ┆ 411.32     │
│ Stafford    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …        ┆ …    ┆ …      ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Kyren       ┆ RB       ┆ LA   ┆ 2025   ┆ … ┆ 351         ┆ 5           ┆ 276.6      ┆ 320.6      │
│ Williams    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Trey        ┆ TE       ┆ ARI  ┆ 2025   ┆ … ┆ 1239        ┆ 11          ┆ 189.9      ┆ 315.9      │
│ McBride     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Dak         ┆ QB       ┆ DAL  ┆ 2025   ┆ … ┆ 0           ┆ 0           ┆ 313.78     ┆ 313.78     │
│ Prescott    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ja'Marr     ┆ WR       ┆ CIN  ┆ 2025   ┆ … ┆ 1412        ┆ 8           ┆ 188.6      ┆ 313.6      │
│ Chase       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jalen Hurts ┆ QB       ┆ PHI  ┆ 2025   ┆ … ┆ 0           ┆ 0           ┆ 313.18     ┆ 313.18     │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# rank players within each position, for the 2025 season
top_qbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "QB")).sort("fantasy_points_ppr", descending=True)
top_rbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "RB")).sort("fantasy_points_ppr", descending=True)
top_wrs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "WR")).sort("fantasy_points_ppr", descending=True)
top_tes = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "TE")).sort("fantasy_points_ppr", descending=True)

top_rbs.head(10)

shape: (10, 17)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 1029        ┆ 9           ┆ 345.4      ┆ 458.4      │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Bijan       ┆ RB       ┆ ATL  ┆ 2025   ┆ … ┆ 820         ┆ 4           ┆ 291.8      ┆ 370.8      │
│ Robinson    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jahmyr      ┆ RB       ┆ DET  ┆ 2025   ┆ … ┆ 616         ┆ 5           ┆ 289.9      ┆ 366.9      │
│ Gibbs       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jonathan    ┆ RB       ┆ IND  ┆ 2025   ┆ … ┆ 378         ┆ 2           ┆ 316.3      ┆ 362.3      │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ James Cook  ┆ RB       ┆ BUF  ┆ 2025   ┆ … ┆ 320         ┆ 2           ┆ 286.4      ┆ 323.4      │
│ De'Von      ┆ RB       ┆ MIA  ┆ 2025   ┆ … ┆ 488         ┆ 4           ┆ 255.8      ┆ 322.8      │
│ Achane      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kyren       ┆ RB       ┆ LA   ┆ 2025   ┆ … ┆ 351         ┆ 5           ┆ 276.6      ┆ 320.6      │
│ Williams    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Chase Brown ┆ RB       ┆ CIN  ┆ 2025   ┆ … ┆ 437         ┆ 5           ┆ 213.6      ┆ 282.6      │
│ Derrick     ┆ RB       ┆ BAL  ┆ 2025   ┆ … ┆ 150         ┆ 0           ┆ 264.5      ┆ 279.5      │
│ Henry       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Travis      ┆ RB       ┆ JAX  ┆ 2025   ┆ … ┆ 341         ┆ 7           ┆ 235.5      ┆ 276.5      │
│ Etienne     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_wrs.head(10)

shape: (10, 17)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Puka Nacua  ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 2047        ┆ 12          ┆ 299.6      ┆ 452.6      │
│ Jaxon Smith ┆ WR       ┆ SEA  ┆ 2025   ┆ … ┆ 1992        ┆ 12          ┆ 272.8      ┆ 408.8      │
│ -Njigba     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Amon-Ra St. ┆ WR       ┆ DET  ┆ 2025   ┆ … ┆ 1401        ┆ 11          ┆ 207.0      ┆ 324.0      │
│ Brown       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ja'Marr     ┆ WR       ┆ CIN  ┆ 2025   ┆ … ┆ 1412        ┆ 8           ┆ 188.6      ┆ 313.6      │
│ Chase       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ George      ┆ WR       ┆ DAL  ┆ 2025   ┆ … ┆ 1429        ┆ 9           ┆ 198.9      ┆ 291.9      │
│ Pickens     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ 2025   ┆ … ┆ 1163        ┆ 9           ┆ 168.0      ┆ 268.0      │
│ Davante     ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 974         ┆ 15          ┆ 187.4      ┆ 258.4      │
│ Adams       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Zay Flowers ┆ WR       ┆ BAL  ┆ 2025   ┆ … ┆ 1211        ┆ 5           ┆ 157.3      ┆ 243.3      │
│ Stefon      ┆ WR       ┆ NE   ┆ 2025   ┆ … ┆ 1123        ┆ 5           ┆ 142.3      ┆ 241.3      │
│ Diggs       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Courtland   ┆ WR       ┆ DEN  ┆ 2025   ┆ … ┆ 1087        ┆ 8           ┆ 158.7      ┆ 239.7      │
│ Sutton      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# recompute season_totals, but also count games played
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("week").n_unique().alias("games_played"),
        pl.col("completions").sum(),
        pl.col("attempts").sum(),
        pl.col("passing_yards").sum(),
        pl.col("passing_tds").sum(),
        pl.col("passing_interceptions").sum(),
        pl.col("carries").sum(),
        pl.col("rushing_yards").sum(),
        pl.col("rushing_tds").sum(),
        pl.col("receptions").sum(),
        pl.col("receiving_yards").sum(),
        pl.col("receiving_tds").sum(),
        pl.col("fantasy_points").sum(),
        pl.col("fantasy_points_ppr").sum(),
    ]
)

# now add points-per-game and efficiency columns
season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

season_totals.head()

shape: (5, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ WR       ┆ GB   ┆ 2024   ┆ … ┆ 105.3       ┆ 7.521429    ┆ 5.75       ┆ 21.37931   │
│ Watson      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kylen       ┆ TE       ┆ IND  ┆ 2024   ┆ … ┆ 32.2        ┆ 2.0125      ┆ NaN        ┆ 13.0       │
│ Granson     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Zay Flowers ┆ WR       ┆ BAL  ┆ 2024   ┆ … ┆ 209.5       ┆ 12.323529   ┆ 6.222222   ┆ 14.310811  │
│ Jayden Reed ┆ WR       ┆ GB   ┆ 2025   ┆ … ┆ 64.2        ┆ 10.7        ┆ 10.5       ┆ 10.869565  │
│ Christian   ┆ WR       ┆ GB   ┆ 2025   ┆ … ┆ 145.0       ┆ 13.181818   ┆ 3.0        ┆ 17.026316  │
│ Watson      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_rbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "RB")).sort("ppr_per_game", descending=True)
top_wrs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "WR")).sort("ppr_per_game", descending=True)
top_qbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "QB")).sort("ppr_per_game", descending=True)
top_tes = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "TE")).sort("ppr_per_game", descending=True)

top_rbs.head(10)

shape: (10, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 458.4       ┆ 24.126316   ┆ 3.813056   ┆ 9.106195   │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Bijan       ┆ RB       ┆ ATL  ┆ 2025   ┆ … ┆ 370.8       ┆ 21.811765   ┆ 5.149826   ┆ 10.379747  │
│ Robinson    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jahmyr      ┆ RB       ┆ DET  ┆ 2025   ┆ … ┆ 366.9       ┆ 21.582353   ┆ 5.032922   ┆ 8.0        │
│ Gibbs       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jonathan    ┆ RB       ┆ IND  ┆ 2025   ┆ … ┆ 362.3       ┆ 21.311765   ┆ 4.907121   ┆ 8.217391   │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ De'Von      ┆ RB       ┆ MIA  ┆ 2025   ┆ … ┆ 322.8       ┆ 20.175      ┆ 5.672269   ┆ 7.283582   │
│ Achane      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ James Cook  ┆ RB       ┆ BUF  ┆ 2025   ┆ … ┆ 323.4       ┆ 17.021053   ┆ 5.126437   ┆ 8.648649   │
│ Chase Brown ┆ RB       ┆ CIN  ┆ 2025   ┆ … ┆ 282.6       ┆ 16.623529   ┆ 4.392241   ┆ 6.333333   │
│ Derrick     ┆ RB       ┆ BAL  ┆ 2025   ┆ … ┆ 279.5       ┆ 16.441176   ┆ 5.19544    ┆ 10.0       │
│ Henry       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kyren       ┆ RB       ┆ LA   ┆ 2025   ┆ … ┆ 320.6       ┆ 16.03       ┆ 4.735974   ┆ 7.977273   │
│ Williams    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Cam         ┆ RB       ┆ NYG  ┆ 2025   ┆ … ┆ 127.7       ┆ 15.9625     ┆ 4.059406   ┆ 8.625      │
│ Skattebo    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# check what season_type values exist and if there are duplicate weeks
data.select(["season_type"]).unique()

shape: (2, 1)
┌─────────────┐
│ season_type │
│ ---         │
│ str         │
╞═════════════╡
│ POST        │
│ REG         │
└─────────────┘

In [ ]:
# check McCaffrey's rows directly to see what's going on
fantasy_data.filter(pl.col("player_display_name") == "Christian McCaffrey")

shape: (42, 18)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ RB       ┆ SF   ┆ 2023   ┆ … ┆ 17          ┆ 0           ┆ 22.9       ┆ 25.9       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2023   ┆ … ┆ 19          ┆ 0           ┆ 19.5       ┆ 22.5       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2023   ┆ … ┆ 34          ┆ 0           ┆ 17.9       ┆ 22.9       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2023   ┆ … ┆ 71          ┆ 1           ┆ 41.7       ┆ 48.7       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2023   ┆ … ┆ 27          ┆ 0           ┆ 11.8       ┆ 13.8       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …        ┆ …    ┆ …      ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 29          ┆ 2           ┆ 26.6       ┆ 32.6       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 41          ┆ 0           ┆ 24.1       ┆ 28.1       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 34          ┆ 0           ┆ 5.7        ┆ 11.7       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 66          ┆ 2           ┆ 23.4       ┆ 29.4       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 39          ┆ 0           ┆ 7.4        ┆ 12.4       │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week", "season_type",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]

fantasy_data = data.select(fantasy_cols)

fantasy_data = fantasy_data.filter(
    (fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])) &
    (fantasy_data["season_type"] == "REG")
)

fantasy_data.head()

shape: (5, 19)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Aaron       ┆ QB       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Rodgers     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Matthew     ┆ QB       ┆ LA   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 14.46      ┆ 14.46      │
│ Stafford    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Randall     ┆ WR       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Cobb        ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tyrod       ┆ QB       ┆ NYG  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.24       ┆ 0.24       │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Brandon     ┆ RB       ┆ LV   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Bolden      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("week").n_unique().alias("games_played"),
        pl.col("completions").sum(),
        pl.col("attempts").sum(),
        pl.col("passing_yards").sum(),
        pl.col("passing_tds").sum(),
        pl.col("passing_interceptions").sum(),
        pl.col("carries").sum(),
        pl.col("rushing_yards").sum(),
        pl.col("rushing_tds").sum(),
        pl.col("receptions").sum(),
        pl.col("receiving_yards").sum(),
        pl.col("receiving_tds").sum(),
        pl.col("fantasy_points").sum(),
        pl.col("fantasy_points_ppr").sum(),
    ]
)

season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

season_totals.head()

shape: (5, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Brenton     ┆ TE       ┆ JAX  ┆ 2023   ┆ … ┆ 14.5        ┆ 2.071429    ┆ NaN        ┆ 7.0        │
│ Strange     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Brevyn      ┆ TE       ┆ DAL  ┆ 2024   ┆ … ┆ 17.8        ┆ 1.618182    ┆ NaN        ┆ 9.777778   │
│ Spann-Ford  ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Trevor      ┆ RB       ┆ CAR  ┆ 2025   ┆ … ┆ 13.7        ┆ 0.805882    ┆ 4.7        ┆ 4.333333   │
│ Etienne     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Taylor      ┆ QB       ┆ ATL  ┆ 2023   ┆ … ┆ 66.0        ┆ 13.2        ┆ 8.266667   ┆ NaN        │
│ Heinicke    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jacory Cros ┆ RB       ┆ WAS  ┆ 2025   ┆ … ┆ 140.3       ┆ 8.252941    ┆ 4.6        ┆ 7.555556   │
│ key-Merritt ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_rbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "RB")).sort("ppr_per_game", descending=True)
top_rbs.head(10)

shape: (10, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Christian   ┆ RB       ┆ SF   ┆ 2025   ┆ … ┆ 416.6       ┆ 24.505882   ┆ 3.864952   ┆ 9.058824   │
│ McCaffrey   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Bijan       ┆ RB       ┆ ATL  ┆ 2025   ┆ … ┆ 370.8       ┆ 21.811765   ┆ 5.149826   ┆ 10.379747  │
│ Robinson    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jahmyr      ┆ RB       ┆ DET  ┆ 2025   ┆ … ┆ 366.9       ┆ 21.582353   ┆ 5.032922   ┆ 8.0        │
│ Gibbs       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Jonathan    ┆ RB       ┆ IND  ┆ 2025   ┆ … ┆ 362.3       ┆ 21.311765   ┆ 4.907121   ┆ 8.217391   │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ De'Von      ┆ RB       ┆ MIA  ┆ 2025   ┆ … ┆ 322.8       ┆ 20.175      ┆ 5.672269   ┆ 7.283582   │
│ Achane      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ James Cook  ┆ RB       ┆ BUF  ┆ 2025   ┆ … ┆ 302.2       ┆ 17.776471   ┆ 5.245955   ┆ 8.818182   │
│ Chase Brown ┆ RB       ┆ CIN  ┆ 2025   ┆ … ┆ 282.6       ┆ 16.623529   ┆ 4.392241   ┆ 6.333333   │
│ Derrick     ┆ RB       ┆ BAL  ┆ 2025   ┆ … ┆ 279.5       ┆ 16.441176   ┆ 5.19544    ┆ 10.0       │
│ Henry       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Cam         ┆ RB       ┆ NYG  ┆ 2025   ┆ … ┆ 127.7       ┆ 15.9625     ┆ 4.059406   ┆ 8.625      │
│ Skattebo    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Josh Jacobs ┆ RB       ┆ GB   ┆ 2025   ┆ … ┆ 237.1       ┆ 15.806667   ┆ 3.970085   ┆ 7.833333   │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_wrs.head(10)

shape: (10, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Puka Nacua  ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 452.6       ┆ 23.821053   ┆ 8.0625     ┆ 13.379085  │
│ Jaxon Smith ┆ WR       ┆ SEA  ┆ 2025   ┆ … ┆ 408.8       ┆ 20.44       ┆ 5.142857   ┆ 14.647059  │
│ -Njigba     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ja'Marr     ┆ WR       ┆ CIN  ┆ 2025   ┆ … ┆ 313.6       ┆ 19.6        ┆ 4.666667   ┆ 11.296     │
│ Chase       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Amon-Ra St. ┆ WR       ┆ DET  ┆ 2025   ┆ … ┆ 324.0       ┆ 19.058824   ┆ 3.0        ┆ 11.974359  │
│ Brown       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Rashee Rice ┆ WR       ┆ KC   ┆ 2025   ┆ … ┆ 150.1       ┆ 18.7625     ┆ 4.0        ┆ 10.773585  │
│ George      ┆ WR       ┆ DAL  ┆ 2025   ┆ … ┆ 291.9       ┆ 17.170588   ┆ NaN        ┆ 15.365591  │
│ Pickens     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Drake       ┆ WR       ┆ ATL  ┆ 2025   ┆ … ┆ 201.9       ┆ 16.825      ┆ NaN        ┆ 13.514706  │
│ London      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ 2025   ┆ … ┆ 268.0       ┆ 16.75       ┆ -3.0       ┆ 11.63      │
│ CeeDee Lamb ┆ WR       ┆ DAL  ┆ 2025   ┆ … ┆ 200.9       ┆ 15.453846   ┆ 2.0        ┆ 14.36      │
│ Davante     ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 258.4       ┆ 15.2        ┆ NaN        ┆ 13.71831   │
│ Adams       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_wrs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "WR")).sort("ppr_per_game", descending=True)
top_wrs.head(10)

shape: (10, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Puka Nacua  ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 375.0       ┆ 23.4375     ┆ 10.5       ┆ 13.294574  │
│ Jaxon Smith ┆ WR       ┆ SEA  ┆ 2025   ┆ … ┆ 359.9       ┆ 21.170588   ┆ 5.142857   ┆ 15.067227  │
│ -Njigba     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ja'Marr     ┆ WR       ┆ CIN  ┆ 2025   ┆ … ┆ 313.6       ┆ 19.6        ┆ 4.666667   ┆ 11.296     │
│ Chase       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Amon-Ra St. ┆ WR       ┆ DET  ┆ 2025   ┆ … ┆ 324.0       ┆ 19.058824   ┆ 3.0        ┆ 11.974359  │
│ Brown       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Rashee Rice ┆ WR       ┆ KC   ┆ 2025   ┆ … ┆ 150.1       ┆ 18.7625     ┆ 4.0        ┆ 10.773585  │
│ George      ┆ WR       ┆ DAL  ┆ 2025   ┆ … ┆ 291.9       ┆ 17.170588   ┆ NaN        ┆ 15.365591  │
│ Pickens     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Drake       ┆ WR       ┆ ATL  ┆ 2025   ┆ … ┆ 201.9       ┆ 16.825      ┆ NaN        ┆ 13.514706  │
│ London      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ 2025   ┆ … ┆ 268.0       ┆ 16.75       ┆ -3.0       ┆ 11.63      │
│ Davante     ┆ WR       ┆ LA   ┆ 2025   ┆ … ┆ 222.9       ┆ 15.921429   ┆ NaN        ┆ 13.15      │
│ Adams       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ CeeDee Lamb ┆ WR       ┆ DAL  ┆ 2025   ┆ … ┆ 200.9       ┆ 15.453846   ┆ 2.0        ┆ 14.36      │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_tes = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "TE")).sort("ppr_per_game", descending=True)
top_tes.head(10)

shape: (10, 21)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Trey        ┆ TE       ┆ ARI  ┆ 2025   ┆ … ┆ 315.9       ┆ 18.582353   ┆ NaN        ┆ 9.833333   │
│ McBride     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Brock       ┆ TE       ┆ LV   ┆ 2025   ┆ … ┆ 176.2       ┆ 14.683333   ┆ 1.0        ┆ 10.625     │
│ Bowers      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ George      ┆ TE       ┆ SF   ┆ 2025   ┆ … ┆ 161.5       ┆ 14.681818   ┆ -3.0       ┆ 11.017544  │
│ Kittle      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tucker      ┆ TE       ┆ GB   ┆ 2025   ┆ … ┆ 117.2       ┆ 14.65       ┆ 3.0        ┆ 15.28125   │
│ Kraft       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ 2025   ┆ … ┆ 210.8       ┆ 12.4        ┆ NaN        ┆ 10.545455  │
│ Dallas      ┆ TE       ┆ PHI  ┆ 2025   ┆ … ┆ 185.1       ┆ 12.34       ┆ NaN        ┆ 9.85       │
│ Goedert     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Sam LaPorta ┆ TE       ┆ DET  ┆ 2025   ┆ … ┆ 106.9       ┆ 11.877778   ┆ NaN        ┆ 12.225     │
│ Harold      ┆ TE       ┆ CLE  ┆ 2025   ┆ … ┆ 186.4       ┆ 11.65       ┆ 1.857143   ┆ 10.152778  │
│ Fannin Jr.  ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Travis      ┆ TE       ┆ KC   ┆ 2025   ┆ … ┆ 193.2       ┆ 11.364706   ┆ 1.0        ┆ 11.197368  │
│ Kelce       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tyler       ┆ TE       ┆ IND  ┆ 2025   ┆ … ┆ 188.5       ┆ 11.088235   ┆ 1.333333   ┆ 10.75      │
│ Warren      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
consistency = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("fantasy_points_ppr").std().alias("ppr_std_dev"),
    ]
)

season_totals = season_totals.join(consistency, on=["player_display_name", "position", "team", "season"])

season_totals.head()

shape: (5, 22)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ ppr_per_gam ┆ yards_per_c ┆ yards_per_ ┆ ppr_std_de │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ e           ┆ arry        ┆ reception  ┆ v          │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Jermar      ┆ RB       ┆ DET  ┆ 2024   ┆ … ┆ 2.1         ┆ 3.666667    ┆ 10.0       ┆ 1.697056   │
│ Jefferson   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ James       ┆ RB       ┆ ARI  ┆ 2024   ┆ … ┆ 15.8625     ┆ 4.635593    ┆ 8.808511   ┆ 7.852378   │
│ Conner      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Ronnie Bell ┆ WR       ┆ SF   ┆ 2023   ┆ … ┆ 2.369231    ┆ NaN         ┆ 11.333333  ┆ 3.770142   │
│ Devontez    ┆ WR       ┆ BAL  ┆ 2025   ┆ … ┆ 4.7         ┆ NaN         ┆ 22.666667  ┆ 6.469268   │
│ Walker      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tahj        ┆ WR       ┆ MIA  ┆ 2025   ┆ … ┆ 2.35        ┆ NaN         ┆ 12.333333  ┆ 3.181981   │
│ Washington  ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_rbs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "RB")).sort("ppr_per_game", descending=True)
top_rbs.select(["player_display_name", "team", "games_played", "ppr_per_game", "ppr_std_dev"]).head(10)

shape: (10, 5)
┌─────────────────────┬──────┬──────────────┬──────────────┬─────────────┐
│ player_display_name ┆ team ┆ games_played ┆ ppr_per_game ┆ ppr_std_dev │
│ ---                 ┆ ---  ┆ ---          ┆ ---          ┆ ---         │
│ str                 ┆ str  ┆ u32          ┆ f64          ┆ f64         │
╞═════════════════════╪══════╪══════════════╪══════════════╪═════════════╡
│ Christian McCaffrey ┆ SF   ┆ 17           ┆ 24.505882    ┆ 8.224466    │
│ Bijan Robinson      ┆ ATL  ┆ 17           ┆ 21.811765    ┆ 10.258404   │
│ Jahmyr Gibbs        ┆ DET  ┆ 17           ┆ 21.582353    ┆ 13.527206   │
│ Jonathan Taylor     ┆ IND  ┆ 17           ┆ 21.311765    ┆ 12.441507   │
│ De'Von Achane       ┆ MIA  ┆ 16           ┆ 20.175       ┆ 7.015364    │
│ James Cook          ┆ BUF  ┆ 17           ┆ 17.776471    ┆ 9.201598    │
│ Chase Brown         ┆ CIN  ┆ 17           ┆ 16.623529    ┆ 7.346132    │
│ Derrick Henry       ┆ BAL  ┆ 17           ┆ 16.441176    ┆ 10.002691   │
│ Cam Skattebo        ┆ NYG  ┆ 8            ┆ 15.9625      ┆ 8.618408    │
│ Josh Jacobs         ┆ GB   ┆ 15           ┆ 15.806667    ┆ 9.019223    │
└─────────────────────┴──────┴──────────────┴──────────────┴─────────────┘

In [ ]:
top_wrs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "WR")).sort("ppr_per_game", descending=True)
top_wrs.select(["player_display_name", "team", "games_played", "ppr_per_game", "ppr_std_dev"]).head(10)

shape: (10, 5)
┌─────────────────────┬──────┬──────────────┬──────────────┬─────────────┐
│ player_display_name ┆ team ┆ games_played ┆ ppr_per_game ┆ ppr_std_dev │
│ ---                 ┆ ---  ┆ ---          ┆ ---          ┆ ---         │
│ str                 ┆ str  ┆ u32          ┆ f64          ┆ f64         │
╞═════════════════════╪══════╪══════════════╪══════════════╪═════════════╡
│ Puka Nacua          ┆ LA   ┆ 16           ┆ 23.4375      ┆ 10.208812   │
│ Jaxon Smith-Njigba  ┆ SEA  ┆ 17           ┆ 21.170588    ┆ 7.481207    │
│ Ja'Marr Chase       ┆ CIN  ┆ 16           ┆ 19.6         ┆ 10.262683   │
│ Amon-Ra St. Brown   ┆ DET  ┆ 17           ┆ 19.058824    ┆ 10.929207   │
│ Rashee Rice         ┆ KC   ┆ 8            ┆ 18.7625      ┆ 8.111533    │
│ George Pickens      ┆ DAL  ┆ 17           ┆ 17.170588    ┆ 9.650632    │
│ Drake London        ┆ ATL  ┆ 12           ┆ 16.825       ┆ 11.453949   │
│ Chris Olave         ┆ NO   ┆ 16           ┆ 16.75        ┆ 7.914291    │
│ Davante Adams       ┆ LA   ┆ 14           ┆ 15.921429    ┆ 6.839386    │
│ CeeDee Lamb         ┆ DAL  ┆ 13           ┆ 15.453846    ┆ 5.98451     │
└─────────────────────┴──────┴──────────────┴──────────────┴─────────────┘

In [ ]:
"targets" in data.columns

True

In [ ]:
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week", "season_type",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "targets", "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]

fantasy_data = data.select(fantasy_cols)

fantasy_data = fantasy_data.filter(
    (fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])) &
    (fantasy_data["season_type"] == "REG")
)

fantasy_data.head()

shape: (5, 20)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ receiving_y ┆ receiving_t ┆ fantasy_po ┆ fantasy_po │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ ards        ┆ ds          ┆ ints       ┆ ints_ppr   │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ i32         ┆ i32         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Aaron       ┆ QB       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Rodgers     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Matthew     ┆ QB       ┆ LA   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 14.46      ┆ 14.46      │
│ Stafford    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Randall     ┆ WR       ┆ NYJ  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Cobb        ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Tyrod       ┆ QB       ┆ NYG  ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.24       ┆ 0.24       │
│ Taylor      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Brandon     ┆ RB       ┆ LV   ┆ 2023   ┆ … ┆ 0           ┆ 0           ┆ 0.0        ┆ 0.0        │
│ Bolden      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("week").n_unique().alias("games_played"),
        pl.col("completions").sum(),
        pl.col("attempts").sum(),
        pl.col("passing_yards").sum(),
        pl.col("passing_tds").sum(),
        pl.col("passing_interceptions").sum(),
        pl.col("carries").sum(),
        pl.col("rushing_yards").sum(),
        pl.col("rushing_tds").sum(),
        pl.col("targets").sum(),
        pl.col("receptions").sum(),
        pl.col("receiving_yards").sum(),
        pl.col("receiving_tds").sum(),
        pl.col("fantasy_points").sum(),
        pl.col("fantasy_points_ppr").sum(),
    ]
)

season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

season_totals.head()

shape: (5, 22)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ fantasy_poi ┆ ppr_per_gam ┆ yards_per_ ┆ yards_per_ │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ nts_ppr     ┆ e           ┆ carry      ┆ reception  │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Joe Milton  ┆ QB       ┆ DAL  ┆ 2025   ┆ … ┆ 10.32       ┆ 2.58        ┆ 10.0       ┆ NaN        │
│ III         ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ C.J. Stroud ┆ QB       ┆ HOU  ┆ 2024   ┆ … ┆ 220.38      ┆ 12.963529   ┆ 4.480769   ┆ NaN        │
│ Travis      ┆ RB       ┆ CHI  ┆ 2025   ┆ … ┆ -0.2        ┆ -0.025      ┆ -2.0       ┆ NaN        │
│ Homer       ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Rashod      ┆ WR       ┆ BAL  ┆ 2023   ┆ … ┆ 76.5        ┆ 5.1         ┆ 18.0       ┆ 11.46875   │
│ Bateman     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Gary        ┆ RB       ┆ NYG  ┆ 2023   ┆ … ┆ 11.6        ┆ 2.9         ┆ 2.111111   ┆ 9.4        │
│ Brightwell  ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
consistency = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg(
    [
        pl.col("fantasy_points_ppr").std().alias("ppr_std_dev"),
    ]
)

season_totals = season_totals.join(consistency, on=["player_display_name", "position", "team", "season"])

season_totals.head()

shape: (5, 23)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ ppr_per_gam ┆ yards_per_c ┆ yards_per_ ┆ ppr_std_de │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ e           ┆ arry        ┆ reception  ┆ v          │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Bijan       ┆ RB       ┆ ATL  ┆ 2024   ┆ … ┆ 20.1        ┆ 4.789474    ┆ 7.065574   ┆ 6.636547   │
│ Robinson    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kaden Davis ┆ WR       ┆ CLE  ┆ 2025   ┆ … ┆ 0.0         ┆ NaN         ┆ NaN        ┆ null       │
│ Greg        ┆ TE       ┆ DEN  ┆ 2023   ┆ … ┆ 2.75        ┆ NaN         ┆ 8.333333   ┆ 2.05061    │
│ Dulcich     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Olamide     ┆ WR       ┆ PHI  ┆ 2023   ┆ … ┆ 3.490909    ┆ NaN         ┆ 16.4       ┆ 4.438345   │
│ Zaccheaus   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Austin      ┆ RB       ┆ WAS  ┆ 2024   ┆ … ┆ 11.025      ┆ 4.766234    ┆ 10.457143  ┆ 5.03445    │
│ Ekeler      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
team_targets = fantasy_data.group_by(["team", "season"]).agg(
    [
        pl.col("targets").sum().alias("team_total_targets"),
    ]
)

team_targets.head()

shape: (5, 3)
┌──────┬────────┬────────────────────┐
│ team ┆ season ┆ team_total_targets │
│ ---  ┆ ---    ┆ ---                │
│ str  ┆ i32    ┆ i32                │
╞══════╪════════╪════════════════════╡
│ NYJ  ┆ 2023   ┆ 562                │
│ LV   ┆ 2023   ┆ 531                │
│ DET  ┆ 2023   ┆ 571                │
│ CAR  ┆ 2023   ┆ 534                │
│ ARI  ┆ 2023   ┆ 540                │
└──────┴────────┴────────────────────┘

In [ ]:
season_totals = season_totals.join(team_targets, on=["team", "season"])

season_totals = season_totals.with_columns([
    (pl.col("targets") / pl.col("team_total_targets") * 100).alias("target_share_pct"),
])

season_totals.head()

shape: (5, 25)
┌─────────────┬──────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ player_disp ┆ position ┆ team ┆ season ┆ … ┆ yards_per_r ┆ ppr_std_dev ┆ team_total ┆ target_sha │
│ lay_name    ┆ ---      ┆ ---  ┆ ---    ┆   ┆ eception    ┆ ---         ┆ _targets   ┆ re_pct     │
│ ---         ┆ str      ┆ str  ┆ i32    ┆   ┆ ---         ┆ f64         ┆ ---        ┆ ---        │
│ str         ┆          ┆      ┆        ┆   ┆ f64         ┆             ┆ i32        ┆ f64        │
╞═════════════╪══════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Bijan       ┆ RB       ┆ ATL  ┆ 2024   ┆ … ┆ 7.065574    ┆ 6.636547    ┆ 539        ┆ 13.358071  │
│ Robinson    ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Kaden Davis ┆ WR       ┆ CLE  ┆ 2025   ┆ … ┆ NaN         ┆ null        ┆ 521        ┆ 0.0        │
│ Greg        ┆ TE       ┆ DEN  ┆ 2023   ┆ … ┆ 8.333333    ┆ 2.05061     ┆ 474        ┆ 0.843882   │
│ Dulcich     ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Olamide     ┆ WR       ┆ PHI  ┆ 2023   ┆ … ┆ 16.4        ┆ 4.438345    ┆ 525        ┆ 3.809524   │
│ Zaccheaus   ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
│ Austin      ┆ RB       ┆ WAS  ┆ 2024   ┆ … ┆ 10.457143   ┆ 5.03445     ┆ 503        ┆ 8.151093   │
│ Ekeler      ┆          ┆      ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
top_wrs = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "WR")).sort("ppr_per_game", descending=True)
top_wrs.select(["player_display_name", "team", "games_played", "ppr_per_game", "ppr_std_dev", "target_share_pct"]).head(10)

shape: (10, 6)
┌─────────────────────┬──────┬──────────────┬──────────────┬─────────────┬──────────────────┐
│ player_display_name ┆ team ┆ games_played ┆ ppr_per_game ┆ ppr_std_dev ┆ target_share_pct │
│ ---                 ┆ ---  ┆ ---          ┆ ---          ┆ ---         ┆ ---              │
│ str                 ┆ str  ┆ u32          ┆ f64          ┆ f64         ┆ f64              │
╞═════════════════════╪══════╪══════════════╪══════════════╪═════════════╪══════════════════╡
│ Puka Nacua          ┆ LA   ┆ 16           ┆ 23.4375      ┆ 10.208812   ┆ 28.571429        │
│ Jaxon Smith-Njigba  ┆ SEA  ┆ 17           ┆ 21.170588    ┆ 7.481207    ┆ 35.824176        │
│ Ja'Marr Chase       ┆ CIN  ┆ 16           ┆ 19.6         ┆ 10.262683   ┆ 30.477759        │
│ Amon-Ra St. Brown   ┆ DET  ┆ 17           ┆ 19.058824    ┆ 10.929207   ┆ 31.272727        │
│ Rashee Rice         ┆ KC   ┆ 8            ┆ 18.7625      ┆ 8.111533    ┆ 14.20765         │
│ George Pickens      ┆ DAL  ┆ 17           ┆ 17.170588    ┆ 9.650632    ┆ 22.570016        │
│ Drake London        ┆ ATL  ┆ 12           ┆ 16.825       ┆ 11.453949   ┆ 21.621622        │
│ Chris Olave         ┆ NO   ┆ 16           ┆ 16.75        ┆ 7.914291    ┆ 27.610619        │
│ Davante Adams       ┆ LA   ┆ 14           ┆ 15.921429    ┆ 6.839386    ┆ 19.621343        │
│ CeeDee Lamb         ┆ DAL  ┆ 13           ┆ 15.453846    ┆ 5.98451     ┆ 19.275124        │
└─────────────────────┴──────┴──────────────┴──────────────┴─────────────┴──────────────────┘

In [ ]:
top_tes = season_totals.filter((pl.col("season") == 2025) & (pl.col("position") == "TE")).sort("ppr_per_game", descending=True)
top_tes.select(["player_display_name", "team", "games_played", "ppr_per_game", "ppr_std_dev", "target_share_pct"]).head(10)

shape: (10, 6)
┌─────────────────────┬──────┬──────────────┬──────────────┬─────────────┬──────────────────┐
│ player_display_name ┆ team ┆ games_played ┆ ppr_per_game ┆ ppr_std_dev ┆ target_share_pct │
│ ---                 ┆ ---  ┆ ---          ┆ ---          ┆ ---         ┆ ---              │
│ str                 ┆ str  ┆ u32          ┆ f64          ┆ f64         ┆ f64              │
╞═════════════════════╪══════╪══════════════╪══════════════╪═════════════╪══════════════════╡
│ Trey McBride        ┆ ARI  ┆ 17           ┆ 18.582353    ┆ 8.366468    ┆ 27.3906          │
│ Brock Bowers        ┆ LV   ┆ 12           ┆ 14.683333    ┆ 10.123675   ┆ 17.444219        │
│ George Kittle       ┆ SF   ┆ 11           ┆ 14.681818    ┆ 8.260244    ┆ 13.243762        │
│ Tucker Kraft        ┆ GB   ┆ 8            ┆ 14.65        ┆ 9.870447    ┆ 9.8434           │
│ Kyle Pitts          ┆ ATL  ┆ 17           ┆ 12.4         ┆ 9.940636    ┆ 22.779923        │
│ Dallas Goedert      ┆ PHI  ┆ 15           ┆ 12.34        ┆ 7.17414     ┆ 17.672414        │
│ Sam LaPorta         ┆ DET  ┆ 9            ┆ 11.877778    ┆ 6.454219    ┆ 8.909091         │
│ Harold Fannin Jr.   ┆ CLE  ┆ 16           ┆ 11.65        ┆ 5.729107    ┆ 20.537428        │
│ Travis Kelce        ┆ KC   ┆ 17           ┆ 11.364706    ┆ 6.405266    ┆ 19.672131        │
│ Tyler Warren        ┆ IND  ┆ 17           ┆ 11.088235    ┆ 4.878381    ┆ 21.172023        │
└─────────────────────┴──────┴──────────────┴──────────────┴─────────────┴──────────────────┘

In [ ]:
season_totals.filter(pl.col("player_display_name") == "Puka Nacua").select(
    ["player_display_name", "season", "games_played", "ppr_per_game", "target_share_pct"]
).sort("season")

shape: (3, 5)
┌─────────────────────┬────────┬──────────────┬──────────────┬──────────────────┐
│ player_display_name ┆ season ┆ games_played ┆ ppr_per_game ┆ target_share_pct │
│ ---                 ┆ ---    ┆ ---          ┆ ---          ┆ ---              │
│ str                 ┆ i32    ┆ u32          ┆ f64          ┆ f64              │
╞═════════════════════╪════════╪══════════════╪══════════════╪══════════════════╡
│ Puka Nacua          ┆ 2023   ┆ 17           ┆ 17.558824    ┆ 28.828829        │
│ Puka Nacua          ┆ 2024   ┆ 11           ┆ 18.781818    ┆ 19.593346        │
│ Puka Nacua          ┆ 2025   ┆ 16           ┆ 23.4375      ┆ 28.571429        │
└─────────────────────┴────────┴──────────────┴──────────────┴──────────────────┘

In [ ]:
trend_table = season_totals.pivot(
    values="ppr_per_game",
    index=["player_display_name", "position"],
    on="season"
)

trend_table.head()

ComputeError: found multiple elements in the same group, please specify an aggregation function

In [ ]:
trend_table = season_totals.pivot(
    values="ppr_per_game",
    index=["player_display_name", "position"],
    on="season",
    aggregate_function="sum"
)

trend_table.head()

shape: (5, 5)
┌─────────────────────┬──────────┬────────┬───────────┬───────────┐
│ player_display_name ┆ position ┆ 2024   ┆ 2025      ┆ 2023      │
│ ---                 ┆ ---      ┆ ---    ┆ ---       ┆ ---       │
│ str                 ┆ str      ┆ f64    ┆ f64       ┆ f64       │
╞═════════════════════╪══════════╪════════╪═══════════╪═══════════╡
│ Bijan Robinson      ┆ RB       ┆ 20.1   ┆ 21.811765 ┆ 14.488235 │
│ Kaden Davis         ┆ WR       ┆ 0.0    ┆ 0.0       ┆ 0.0       │
│ Greg Dulcich        ┆ TE       ┆ 2.6    ┆ 6.977778  ┆ 2.75      │
│ Olamide Zaccheaus   ┆ WR       ┆ 7.15   ┆ 6.057143  ┆ 3.490909  │
│ Austin Ekeler       ┆ RB       ┆ 11.025 ┆ 6.55      ┆ 13.242857 │
└─────────────────────┴──────────┴────────┴───────────┴───────────┘

In [ ]:
trend_table = trend_table.with_columns([
    (pl.col("2025") - pl.col("2024")).alias("ppr_change_24_to_25")
])

trend_table.sort("ppr_change_24_to_25", descending=True).head(15)

shape: (15, 6)
┌─────────────────────┬──────────┬──────┬───────────┬───────┬─────────────────────┐
│ player_display_name ┆ position ┆ 2024 ┆ 2025      ┆ 2023  ┆ ppr_change_24_to_25 │
│ ---                 ┆ ---      ┆ ---  ┆ ---       ┆ ---   ┆ ---                 │
│ str                 ┆ str      ┆ f64  ┆ f64       ┆ f64   ┆ f64                 │
╞═════════════════════╪══════════╪══════╪═══════════╪═══════╪═════════════════════╡
│ Jaxson Dart         ┆ QB       ┆ 0.0  ┆ 17.255714 ┆ 0.0   ┆ 17.255714           │
│ Cam Skattebo        ┆ RB       ┆ 0.0  ┆ 15.9625   ┆ 0.0   ┆ 15.9625             │
│ Omarion Hampton     ┆ RB       ┆ 0.0  ┆ 15.077778 ┆ 0.0   ┆ 15.077778           │
│ Ashton Jeanty       ┆ RB       ┆ 0.0  ┆ 14.417647 ┆ 0.0   ┆ 14.417647           │
│ Tyler Shough        ┆ QB       ┆ 0.0  ┆ 14.36     ┆ 0.0   ┆ 14.36               │
│ …                   ┆ …        ┆ …    ┆ …         ┆ …     ┆ …                   │
│ Quinshon Judkins    ┆ RB       ┆ 0.0  ┆ 12.128571 ┆ 0.0   ┆ 12.128571           │
│ Carson Wentz        ┆ QB       ┆ 2.36 ┆ 14.068    ┆ 26.12 ┆ 11.708              │
│ Harold Fannin Jr.   ┆ TE       ┆ 0.0  ┆ 11.65     ┆ 0.0   ┆ 11.65               │
│ Emeka Egbuka        ┆ WR       ┆ 0.0  ┆ 11.511765 ┆ 0.0   ┆ 11.511765           │
│ Tyler Warren        ┆ TE       ┆ 0.0  ┆ 11.088235 ┆ 0.0   ┆ 11.088235           │
└─────────────────────┴──────────┴──────┴───────────┴───────┴─────────────────────┘

In [ ]:
established_trends = trend_table.filter(
    (pl.col("2024") > 5) & (pl.col("2025") > 5)
)

established_trends.sort("ppr_change_24_to_25", descending=True).head(15)

shape: (15, 6)
┌─────────────────────┬──────────┬───────────┬───────────┬───────────┬─────────────────────┐
│ player_display_name ┆ position ┆ 2024      ┆ 2025      ┆ 2023      ┆ ppr_change_24_to_25 │
│ ---                 ┆ ---      ┆ ---       ┆ ---       ┆ ---       ┆ ---                 │
│ str                 ┆ str      ┆ f64       ┆ f64       ┆ f64       ┆ f64                 │
╞═════════════════════╪══════════╪═══════════╪═══════════╪═══════════╪═════════════════════╡
│ Christian McCaffrey ┆ RB       ┆ 11.95     ┆ 24.505882 ┆ 24.45625  ┆ 12.555882           │
│ Jacoby Brissett     ┆ QB       ┆ 6.462857  ┆ 16.245714 ┆ 11.43     ┆ 9.782857            │
│ Matthew Stafford    ┆ QB       ┆ 13.41125  ┆ 20.610588 ┆ 16.206667 ┆ 7.199338            │
│ Jakobi Meyers       ┆ WR       ┆ 14.533333 ┆ 21.698413 ┆ 13.66125  ┆ 7.165079            │
│ Chris Olave         ┆ WR       ┆ 9.5875    ┆ 16.75     ┆ 14.45625  ┆ 7.1625              │
│ …                   ┆ …        ┆ …         ┆ …         ┆ …         ┆ …                   │
│ Christian Watson    ┆ WR       ┆ 7.521429  ┆ 13.24     ┆ 11.255556 ┆ 5.718571            │
│ George Pickens      ┆ WR       ┆ 11.742857 ┆ 17.170588 ┆ 12.282353 ┆ 5.427731            │
│ Trevor Lawrence     ┆ QB       ┆ 14.52     ┆ 19.892941 ┆ 16.40875  ┆ 5.372941            │
│ Jaylen Warren       ┆ RB       ┆ 8.273333  ┆ 13.56875  ┆ 11.552941 ┆ 5.295417            │
│ Michael Wilson      ┆ WR       ┆ 7.78125   ┆ 12.976471 ┆ 8.807692  ┆ 5.195221            │
└─────────────────────┴──────────┴───────────┴───────────┴───────────┴─────────────────────┘

In [ ]:
draft_board = season_totals.filter(pl.col("season") == 2025).select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct"
])

draft_board.head()

shape: (5, 7)
┌──────────────────┬──────────┬──────┬──────────────┬──────────────┬─────────────┬─────────────────┐
│ player_display_n ┆ position ┆ team ┆ games_played ┆ ppr_per_game ┆ ppr_std_dev ┆ target_share_pc │
│ ame              ┆ ---      ┆ ---  ┆ ---          ┆ ---          ┆ ---         ┆ t               │
│ ---              ┆ str      ┆ str  ┆ u32          ┆ f64          ┆ f64         ┆ ---             │
│ str              ┆          ┆      ┆              ┆              ┆             ┆ f64             │
╞══════════════════╪══════════╪══════╪══════════════╪══════════════╪═════════════╪═════════════════╡
│ Kaden Davis      ┆ WR       ┆ CLE  ┆ 1            ┆ 0.0          ┆ null        ┆ 0.0             │
│ Javonte Williams ┆ RB       ┆ DAL  ┆ 16           ┆ 15.175       ┆ 6.017031    ┆ 8.401977        │
│ Emari Demercado  ┆ RB       ┆ ARI  ┆ 12           ┆ 4.858333     ┆ 4.298934    ┆ 3.241491        │
│ Bryce Oliver     ┆ WR       ┆ TEN  ┆ 2            ┆ 0.9          ┆ 1.272792    ┆ 0.189036        │
│ Dylan Sampson    ┆ RB       ┆ CLE  ┆ 15           ┆ 5.84         ┆ 5.598061    ┆ 7.677543        │
└──────────────────┴──────────┴──────┴──────────────┴──────────────┴─────────────┴─────────────────┘

In [ ]:
draft_board = season_totals.filter(pl.col("season") == 2025).select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception"
])

draft_board.head()

shape: (5, 9)
┌────────────┬──────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_dis ┆ position ┆ team ┆ games_play ┆ … ┆ ppr_std_de ┆ target_sha ┆ yards_per_ ┆ yards_per │
│ play_name  ┆ ---      ┆ ---  ┆ ed         ┆   ┆ v          ┆ re_pct     ┆ carry      ┆ _receptio │
│ ---        ┆ str      ┆ str  ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ n         │
│ str        ┆          ┆      ┆ u32        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│            ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆ f64       │
╞════════════╪══════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Kaden      ┆ WR       ┆ CLE  ┆ 1          ┆ … ┆ null       ┆ 0.0        ┆ NaN        ┆ NaN       │
│ Davis      ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Javonte    ┆ RB       ┆ DAL  ┆ 16         ┆ … ┆ 6.017031   ┆ 8.401977   ┆ 4.765873   ┆ 3.914286  │
│ Williams   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Emari      ┆ RB       ┆ ARI  ┆ 12         ┆ … ┆ 4.298934   ┆ 3.241491   ┆ 7.090909   ┆ 7.769231  │
│ Demercado  ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Bryce      ┆ WR       ┆ TEN  ┆ 2          ┆ … ┆ 1.272792   ┆ 0.189036   ┆ NaN        ┆ 8.0       │
│ Oliver     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Dylan      ┆ RB       ┆ CLE  ┆ 15         ┆ … ┆ 5.598061   ┆ 7.677543   ┆ 2.692308   ┆ 8.212121  │
│ Sampson    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
draft_board = draft_board.join(
    established_trends.select(["player_display_name", "ppr_change_24_to_25"]),
    on="player_display_name",
    how="left"
)

draft_board.head()

shape: (5, 10)
┌────────────┬──────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_dis ┆ position ┆ team ┆ games_play ┆ … ┆ target_sha ┆ yards_per_ ┆ yards_per_ ┆ ppr_chang │
│ play_name  ┆ ---      ┆ ---  ┆ ed         ┆   ┆ re_pct     ┆ carry      ┆ reception  ┆ e_24_to_2 │
│ ---        ┆ str      ┆ str  ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ 5         │
│ str        ┆          ┆      ┆ u32        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│            ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆ f64       │
╞════════════╪══════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Kaden      ┆ WR       ┆ CLE  ┆ 1          ┆ … ┆ 0.0        ┆ NaN        ┆ NaN        ┆ null      │
│ Davis      ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Javonte    ┆ RB       ┆ DAL  ┆ 16         ┆ … ┆ 8.401977   ┆ 4.765873   ┆ 3.914286   ┆ 5.886765  │
│ Williams   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Emari      ┆ RB       ┆ ARI  ┆ 12         ┆ … ┆ 3.241491   ┆ 7.090909   ┆ 7.769231   ┆ null      │
│ Demercado  ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Bryce      ┆ WR       ┆ TEN  ┆ 2          ┆ … ┆ 0.189036   ┆ NaN        ┆ 8.0        ┆ null      │
│ Oliver     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Dylan      ┆ RB       ┆ CLE  ┆ 15         ┆ … ┆ 7.677543   ┆ 2.692308   ┆ 8.212121   ┆ null      │
│ Sampson    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
draft_board = draft_board.with_columns([
    pl.col("ppr_per_game").rank(method="ordinal", descending=True).over("position").alias("position_rank")
])

draft_board.sort(["position", "position_rank"]).head(15)

shape: (15, 11)
┌────────────┬──────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_dis ┆ position ┆ team ┆ games_play ┆ … ┆ yards_per_ ┆ yards_per_ ┆ ppr_change ┆ position_ │
│ play_name  ┆ ---      ┆ ---  ┆ ed         ┆   ┆ carry      ┆ reception  ┆ _24_to_25  ┆ rank      │
│ ---        ┆ str      ┆ str  ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ str        ┆          ┆      ┆ u32        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ u32       │
╞════════════╪══════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Josh Allen ┆ QB       ┆ BUF  ┆ 16         ┆ … ┆ 5.169643   ┆ NaN        ┆ -0.90125   ┆ 1         │
│ Drake Maye ┆ QB       ┆ NE   ┆ 17         ┆ … ┆ 4.368932   ┆ 2.0        ┆ 7.077376   ┆ 2         │
│ Matthew    ┆ QB       ┆ LA   ┆ 17         ┆ … ┆ 0.034483   ┆ NaN        ┆ 7.199338   ┆ 3         │
│ Stafford   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Patrick    ┆ QB       ┆ KC   ┆ 14         ┆ … ┆ 6.59375    ┆ -10.0      ┆ 2.716964   ┆ 4         │
│ Mahomes    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Trevor     ┆ QB       ┆ JAX  ┆ 17         ┆ … ┆ 4.378049   ┆ NaN        ┆ 5.372941   ┆ 5         │
│ Lawrence   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …        ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ Justin     ┆ QB       ┆ LAC  ┆ 16         ┆ … ┆ 6.0        ┆ NaN        ┆ 1.141765   ┆ 11        │
│ Herbert    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Jared Goff ┆ QB       ┆ DET  ┆ 17         ┆ … ┆ 2.368421   ┆ NaN        ┆ -1.611765  ┆ 12        │
│ Daniel     ┆ QB       ┆ IND  ┆ 13         ┆ … ┆ 3.644444   ┆ NaN        ┆ 3.888462   ┆ 13        │
│ Jones      ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Jaxson     ┆ QB       ┆ NYG  ┆ 14         ┆ … ┆ 5.662791   ┆ NaN        ┆ null       ┆ 14        │
│ Dart       ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Joe Burrow ┆ QB       ┆ CIN  ┆ 8          ┆ … ┆ 2.928571   ┆ NaN        ┆ -5.123088  ┆ 15        │
└────────────┴──────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
draft_board = draft_board.with_columns([
    pl.when(pl.col("position_rank") <= 3).then(1)
    .when(pl.col("position_rank") <= 8).then(2)
    .when(pl.col("position_rank") <= 15).then(3)
    .when(pl.col("position_rank") <= 24).then(4)
    .otherwise(5)
    .alias("tier")
])

draft_board.sort(["position", "position_rank"]).head(15)

shape: (15, 12)
┌─────────────┬──────────┬──────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬──────┐
│ player_disp ┆ position ┆ team ┆ games_playe ┆ … ┆ yards_per_r ┆ ppr_change_ ┆ position_ra ┆ tier │
│ lay_name    ┆ ---      ┆ ---  ┆ d           ┆   ┆ eception    ┆ 24_to_25    ┆ nk          ┆ ---  │
│ ---         ┆ str      ┆ str  ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ i32  │
│ str         ┆          ┆      ┆ u32         ┆   ┆ f64         ┆ f64         ┆ u32         ┆      │
╞═════════════╪══════════╪══════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪══════╡
│ Josh Allen  ┆ QB       ┆ BUF  ┆ 16          ┆ … ┆ NaN         ┆ -0.90125    ┆ 1           ┆ 1    │
│ Drake Maye  ┆ QB       ┆ NE   ┆ 17          ┆ … ┆ 2.0         ┆ 7.077376    ┆ 2           ┆ 1    │
│ Matthew     ┆ QB       ┆ LA   ┆ 17          ┆ … ┆ NaN         ┆ 7.199338    ┆ 3           ┆ 1    │
│ Stafford    ┆          ┆      ┆             ┆   ┆             ┆             ┆             ┆      │
│ Patrick     ┆ QB       ┆ KC   ┆ 14          ┆ … ┆ -10.0       ┆ 2.716964    ┆ 4           ┆ 2    │
│ Mahomes     ┆          ┆      ┆             ┆   ┆             ┆             ┆             ┆      │
│ Trevor      ┆ QB       ┆ JAX  ┆ 17          ┆ … ┆ NaN         ┆ 5.372941    ┆ 5           ┆ 2    │
│ Lawrence    ┆          ┆      ┆             ┆   ┆             ┆             ┆             ┆      │
│ …           ┆ …        ┆ …    ┆ …           ┆ … ┆ …           ┆ …           ┆ …           ┆ …    │
│ Justin      ┆ QB       ┆ LAC  ┆ 16          ┆ … ┆ NaN         ┆ 1.141765    ┆ 11          ┆ 3    │
│ Herbert     ┆          ┆      ┆             ┆   ┆             ┆             ┆             ┆      │
│ Jared Goff  ┆ QB       ┆ DET  ┆ 17          ┆ … ┆ NaN         ┆ -1.611765   ┆ 12          ┆ 3    │
│ Daniel      ┆ QB       ┆ IND  ┆ 13          ┆ … ┆ NaN         ┆ 3.888462    ┆ 13          ┆ 3    │
│ Jones       ┆          ┆      ┆             ┆   ┆             ┆             ┆             ┆      │
│ Jaxson Dart ┆ QB       ┆ NYG  ┆ 14          ┆ … ┆ NaN         ┆ null        ┆ 14          ┆ 3    │
│ Joe Burrow  ┆ QB       ┆ CIN  ┆ 8           ┆ … ┆ NaN         ┆ -5.123088   ┆ 15          ┆ 3    │
└─────────────┴──────────┴──────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴──────┘

In [ ]:
draft_board = draft_board.with_columns([
    pl.col("ppr_change_24_to_25").fill_null(0).alias("ppr_change_filled")
])

draft_board = draft_board.with_columns([
    (
        pl.col("ppr_per_game")
        - (0.3 * pl.col("ppr_std_dev").fill_null(0))
        + (0.3 * pl.col("ppr_change_filled"))
    ).alias("composite_score")
])

draft_board.select(["player_display_name", "position", "ppr_per_game", "ppr_std_dev", "ppr_change_24_to_25", "composite_score"]).sort("composite_score", descending=True).head(10)

shape: (10, 6)
┌────────────────────┬──────────┬──────────────┬─────────────┬───────────────────┬─────────────────┐
│ player_display_nam ┆ position ┆ ppr_per_game ┆ ppr_std_dev ┆ ppr_change_24_to_ ┆ composite_score │
│ e                  ┆ ---      ┆ ---          ┆ ---         ┆ 25                ┆ ---             │
│ ---                ┆ str      ┆ f64          ┆ f64         ┆ ---               ┆ f64             │
│ str                ┆          ┆              ┆             ┆ f64               ┆                 │
╞════════════════════╪══════════╪══════════════╪═════════════╪═══════════════════╪═════════════════╡
│ Christian          ┆ RB       ┆ 24.505882    ┆ 8.224466    ┆ 12.555882         ┆ 25.805307       │
│ McCaffrey          ┆          ┆              ┆             ┆                   ┆                 │
│ Puka Nacua         ┆ WR       ┆ 23.4375      ┆ 10.208812   ┆ 4.655682          ┆ 21.771561       │
│ Drake Maye         ┆ QB       ┆ 20.703529    ┆ 5.388322    ┆ 7.077376          ┆ 21.210246       │
│ Jaxon Smith-Njigba ┆ WR       ┆ 21.170588    ┆ 7.481207    ┆ 6.288235          ┆ 20.812697       │
│ Matthew Stafford   ┆ QB       ┆ 20.610588    ┆ 6.979442    ┆ 7.199338          ┆ 20.676557       │
│ Josh Allen         ┆ QB       ┆ 22.78875     ┆ 10.404942   ┆ -0.90125          ┆ 19.396892       │
│ Bijan Robinson     ┆ RB       ┆ 21.811765    ┆ 10.258404   ┆ 1.711765          ┆ 19.247773       │
│ Trevor Lawrence    ┆ QB       ┆ 19.892941    ┆ 8.785508    ┆ 5.372941          ┆ 18.869171       │
│ De'Von Achane      ┆ RB       ┆ 20.175       ┆ 7.015364    ┆ 2.533824          ┆ 18.830538       │
│ Patrick Mahomes    ┆ QB       ┆ 20.405714    ┆ 7.9956      ┆ 2.716964          ┆ 18.822123       │
└────────────────────┴──────────┴──────────────┴─────────────┴───────────────────┴─────────────────┘

In [ ]:
draft_board = draft_board.with_columns([
    pl.col("composite_score").rank(method="ordinal", descending=True).over("position").alias("position_rank")
])

draft_board = draft_board.with_columns([
    pl.when(pl.col("position_rank") <= 3).then(1)
    .when(pl.col("position_rank") <= 8).then(2)
    .when(pl.col("position_rank") <= 15).then(3)
    .when(pl.col("position_rank") <= 24).then(4)
    .otherwise(5)
    .alias("tier")
])

draft_board.sort(["position", "position_rank"]).head(15)

shape: (15, 14)
┌─────────────┬──────────┬──────┬─────────────┬───┬─────────────┬──────┬─────────────┬─────────────┐
│ player_disp ┆ position ┆ team ┆ games_playe ┆ … ┆ position_ra ┆ tier ┆ ppr_change_ ┆ composite_s │
│ lay_name    ┆ ---      ┆ ---  ┆ d           ┆   ┆ nk          ┆ ---  ┆ filled      ┆ core        │
│ ---         ┆ str      ┆ str  ┆ ---         ┆   ┆ ---         ┆ i32  ┆ ---         ┆ ---         │
│ str         ┆          ┆      ┆ u32         ┆   ┆ u32         ┆      ┆ f64         ┆ f64         │
╞═════════════╪══════════╪══════╪═════════════╪═══╪═════════════╪══════╪═════════════╪═════════════╡
│ Drake Maye  ┆ QB       ┆ NE   ┆ 17          ┆ … ┆ 1           ┆ 1    ┆ 7.077376    ┆ 21.210246   │
│ Matthew     ┆ QB       ┆ LA   ┆ 17          ┆ … ┆ 2           ┆ 1    ┆ 7.199338    ┆ 20.676557   │
│ Stafford    ┆          ┆      ┆             ┆   ┆             ┆      ┆             ┆             │
│ Josh Allen  ┆ QB       ┆ BUF  ┆ 16          ┆ … ┆ 3           ┆ 1    ┆ -0.90125    ┆ 19.396892   │
│ Trevor      ┆ QB       ┆ JAX  ┆ 17          ┆ … ┆ 4           ┆ 2    ┆ 5.372941    ┆ 18.869171   │
│ Lawrence    ┆          ┆      ┆             ┆   ┆             ┆      ┆             ┆             │
│ Patrick     ┆ QB       ┆ KC   ┆ 14          ┆ … ┆ 5           ┆ 2    ┆ 2.716964    ┆ 18.822123   │
│ Mahomes     ┆          ┆      ┆             ┆   ┆             ┆      ┆             ┆             │
│ …           ┆ …        ┆ …    ┆ …           ┆ … ┆ …           ┆ …    ┆ …           ┆ …           │
│ Justin      ┆ QB       ┆ LAC  ┆ 16          ┆ … ┆ 11          ┆ 3    ┆ 1.141765    ┆ 15.950278   │
│ Herbert     ┆          ┆      ┆             ┆   ┆             ┆      ┆             ┆             │
│ Jalen Hurts ┆ QB       ┆ PHI  ┆ 16          ┆ … ┆ 12          ┆ 3    ┆ -2.19175    ┆ 15.883814   │
│ Bo Nix      ┆ QB       ┆ DEN  ┆ 17          ┆ … ┆ 13          ┆ 3    ┆ -0.727059   ┆ 15.202651   │
│ Jared Goff  ┆ QB       ┆ DET  ┆ 17          ┆ … ┆ 14          ┆ 3    ┆ -1.611765   ┆ 14.735195   │
│ Kyler       ┆ QB       ┆ ARI  ┆ 5           ┆ … ┆ 15          ┆ 3    ┆ -1.928706   ┆ 14.443668   │
│ Murray      ┆          ┆      ┆             ┆   ┆             ┆      ┆             ┆             │
└─────────────┴──────────┴──────┴─────────────┴───┴─────────────┴──────┴─────────────┴─────────────┘

In [ ]:
draft_board.sort(["position", "position_rank"]).write_csv("fantasy_draft_board_2025.csv")

In [ ]:
replacement_levels = {}

for pos, cutoff in [("QB", 20), ("RB", 31), ("WR", 31), ("TE", 14)]:
    player_at_cutoff = draft_board.filter(
        (pl.col("position") == pos) & (pl.col("position_rank") == cutoff)
    )
    replacement_levels[pos] = player_at_cutoff["composite_score"][0]

replacement_levels

{'QB': 13.034964125853703,
 'RB': 8.535834438551902,
 'WR': 10.049780156161475,
 'TE': 9.366056872253003}

In [ ]:
draft_board = draft_board.with_columns([
    pl.when(pl.col("position") == "QB").then(pl.col("composite_score") - replacement_levels["QB"])
    .when(pl.col("position") == "RB").then(pl.col("composite_score") - replacement_levels["RB"])
    .when(pl.col("position") == "WR").then(pl.col("composite_score") - replacement_levels["WR"])
    .when(pl.col("position") == "TE").then(pl.col("composite_score") - replacement_levels["TE"])
    .alias("vorp")
])

draft_board.sort("vorp", descending=True).select(
    ["player_display_name", "position", "composite_score", "vorp"]
).head(15)

shape: (15, 4)
┌─────────────────────┬──────────┬─────────────────┬───────────┐
│ player_display_name ┆ position ┆ composite_score ┆ vorp      │
│ ---                 ┆ ---      ┆ ---             ┆ ---       │
│ str                 ┆ str      ┆ f64             ┆ f64       │
╞═════════════════════╪══════════╪═════════════════╪═══════════╡
│ Christian McCaffrey ┆ RB       ┆ 25.805307       ┆ 17.269473 │
│ Puka Nacua          ┆ WR       ┆ 21.771561       ┆ 11.721781 │
│ Jaxon Smith-Njigba  ┆ WR       ┆ 20.812697       ┆ 10.762917 │
│ Bijan Robinson      ┆ RB       ┆ 19.247773       ┆ 10.711938 │
│ De'Von Achane       ┆ RB       ┆ 18.830538       ┆ 10.294703 │
│ …                   ┆ …        ┆ …               ┆ …         │
│ Rashee Rice         ┆ WR       ┆ 17.09029        ┆ 7.04051   │
│ James Cook          ┆ RB       ┆ 15.348307       ┆ 6.812473  │
│ Javonte Williams    ┆ RB       ┆ 15.13592        ┆ 6.600086  │
│ Chris Olave         ┆ WR       ┆ 16.524463       ┆ 6.474683  │
│ Josh Allen          ┆ QB       ┆ 19.396892       ┆ 6.361928  │
└─────────────────────┴──────────┴─────────────────┴───────────┘

In [ ]:
draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).head(15)

shape: (15, 14)
┌──────────────┬──────────┬──────┬──────────────┬───┬──────────────┬─────────────┬──────┬──────────┐
│ player_displ ┆ position ┆ team ┆ games_played ┆ … ┆ composite_sc ┆ position_ra ┆ tier ┆ vorp     │
│ ay_name      ┆ ---      ┆ ---  ┆ ---          ┆   ┆ ore          ┆ nk          ┆ ---  ┆ ---      │
│ ---          ┆ str      ┆ str  ┆ u32          ┆   ┆ ---          ┆ ---         ┆ i32  ┆ f64      │
│ str          ┆          ┆      ┆              ┆   ┆ f64          ┆ u32         ┆      ┆          │
╞══════════════╪══════════╪══════╪══════════════╪═══╪══════════════╪═════════════╪══════╪══════════╡
│ Drake Maye   ┆ QB       ┆ NE   ┆ 17           ┆ … ┆ 21.210246    ┆ 1           ┆ 1    ┆ 8.175281 │
│ Matthew      ┆ QB       ┆ LA   ┆ 17           ┆ … ┆ 20.676557    ┆ 2           ┆ 1    ┆ 7.641593 │
│ Stafford     ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Josh Allen   ┆ QB       ┆ BUF  ┆ 16           ┆ … ┆ 19.396892    ┆ 3           ┆ 1    ┆ 6.361928 │
│ Trevor       ┆ QB       ┆ JAX  ┆ 17           ┆ … ┆ 18.869171    ┆ 4           ┆ 2    ┆ 5.834207 │
│ Lawrence     ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Patrick      ┆ QB       ┆ KC   ┆ 14           ┆ … ┆ 18.822123    ┆ 5           ┆ 2    ┆ 5.787159 │
│ Mahomes      ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ …            ┆ …        ┆ …    ┆ …            ┆ … ┆ …            ┆ …           ┆ …    ┆ …        │
│ Justin       ┆ QB       ┆ LAC  ┆ 16           ┆ … ┆ 15.950278    ┆ 11          ┆ 3    ┆ 2.915314 │
│ Herbert      ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Jalen Hurts  ┆ QB       ┆ PHI  ┆ 16           ┆ … ┆ 15.883814    ┆ 12          ┆ 3    ┆ 2.848849 │
│ Bo Nix       ┆ QB       ┆ DEN  ┆ 17           ┆ … ┆ 15.202651    ┆ 13          ┆ 3    ┆ 2.167686 │
│ Jared Goff   ┆ QB       ┆ DET  ┆ 17           ┆ … ┆ 14.735195    ┆ 14          ┆ 3    ┆ 1.700231 │
│ Kyler Murray ┆ QB       ┆ ARI  ┆ 5            ┆ … ┆ 14.443668    ┆ 15          ┆ 3    ┆ 1.408704 │
└──────────────┴──────────┴──────┴──────────────┴───┴──────────────┴─────────────┴──────┴──────────┘

In [ ]:
career_stats = season_totals.group_by("player_display_name").agg([
    pl.col("ppr_per_game").mean().alias("career_avg_ppr"),
    pl.col("games_played").sum().alias("career_games_played"),
])

career_stats.head()

shape: (5, 3)
┌─────────────────────┬────────────────┬─────────────────────┐
│ player_display_name ┆ career_avg_ppr ┆ career_games_played │
│ ---                 ┆ ---            ┆ ---                 │
│ str                 ┆ f64            ┆ u32                 │
╞═════════════════════╪════════════════╪═════════════════════╡
│ Tre' McKitty        ┆ 0.0            ┆ 1                   │
│ LeQuint Allen Jr.   ┆ 1.55           ┆ 16                  │
│ Xavier Smith        ┆ 1.730804       ┆ 30                  │
│ Will Mallory        ┆ 2.367965       ┆ 19                  │
│ Kadarius Toney      ┆ 1.971795       ┆ 16                  │
└─────────────────────┴────────────────┴─────────────────────┘

In [ ]:
draft_board = draft_board.join(career_stats, on="player_display_name", how="left")

draft_board.select([
    "player_display_name", "position", "ppr_per_game", "career_avg_ppr", "career_games_played", "vorp"
]).sort(["position", "position_rank"]).head(15)

ColumnNotFoundError: unable to find column "position_rank"; valid columns: ["player_display_name", "position", "ppr_per_game", "career_avg_ppr", "career_games_played", "vorp"]

In [ ]:
draft_board.select([
    "player_display_name", "position", "ppr_per_game", "career_avg_ppr", "career_games_played", "position_rank", "vorp"
]).sort(["position", "position_rank"]).head(15)

shape: (15, 7)
┌───────────────┬──────────┬──────────────┬───────────────┬──────────────┬──────────────┬──────────┐
│ player_displa ┆ position ┆ ppr_per_game ┆ career_avg_pp ┆ career_games ┆ position_ran ┆ vorp     │
│ y_name        ┆ ---      ┆ ---          ┆ r             ┆ _played      ┆ k            ┆ ---      │
│ ---           ┆ str      ┆ f64          ┆ ---           ┆ ---          ┆ ---          ┆ f64      │
│ str           ┆          ┆              ┆ f64           ┆ u32          ┆ u32          ┆          │
╞═══════════════╪══════════╪══════════════╪═══════════════╪══════════════╪══════════════╪══════════╡
│ Drake Maye    ┆ QB       ┆ 20.703529    ┆ 17.164842     ┆ 30           ┆ 1            ┆ 8.175281 │
│ Matthew       ┆ QB       ┆ 20.610588    ┆ 16.742835     ┆ 48           ┆ 2            ┆ 7.641593 │
│ Stafford      ┆          ┆              ┆               ┆              ┆              ┆          │
│ Josh Allen    ┆ QB       ┆ 22.78875     ┆ 23.19174      ┆ 49           ┆ 3            ┆ 6.361928 │
│ Trevor        ┆ QB       ┆ 19.892941    ┆ 16.940564     ┆ 43           ┆ 4            ┆ 5.834207 │
│ Lawrence      ┆          ┆              ┆               ┆              ┆              ┆          │
│ Patrick       ┆ QB       ┆ 20.405714    ┆ 18.536071     ┆ 46           ┆ 5            ┆ 5.787159 │
│ Mahomes       ┆          ┆              ┆               ┆              ┆              ┆          │
│ …             ┆ …        ┆ …            ┆ …             ┆ …            ┆ …            ┆ …        │
│ Justin        ┆ QB       ┆ 17.93        ┆ 17.576848     ┆ 46           ┆ 11           ┆ 2.915314 │
│ Herbert       ┆          ┆              ┆               ┆              ┆              ┆          │
│ Jalen Hurts   ┆ QB       ┆ 18.81625     ┆ 20.271221     ┆ 48           ┆ 12           ┆ 2.848849 │
│ Bo Nix        ┆ QB       ┆ 17.931765    ┆ 18.295294     ┆ 34           ┆ 13           ┆ 2.167686 │
│ Jared Goff    ┆ QB       ┆ 17.474118    ┆ 17.855294     ┆ 51           ┆ 14           ┆ 1.700231 │
│ Kyler Murray  ┆ QB       ┆ 15.556       ┆ 17.111902     ┆ 30           ┆ 15           ┆ 1.408704 │
└───────────────┴──────────┴──────────────┴───────────────┴──────────────┴──────────────┴──────────┘

In [ ]:
draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "career_games_played",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).write_csv("fantasy_draft_board_complete.csv")

In [ ]:
seasons_active = season_totals.group_by("player_display_name").agg([
    pl.col("season").n_unique().alias("seasons_active")
])

seasons_active.head()

shape: (5, 2)
┌─────────────────────┬────────────────┐
│ player_display_name ┆ seasons_active │
│ ---                 ┆ ---            │
│ str                 ┆ u32            │
╞═════════════════════╪════════════════╡
│ Alexander Mattison  ┆ 2              │
│ Devin Duvernay      ┆ 3              │
│ Cooper Kupp         ┆ 3              │
│ Jesper Horsted      ┆ 1              │
│ Chris Blair         ┆ 2              │
└─────────────────────┴────────────────┘

In [ ]:
draft_board = draft_board.join(seasons_active, on="player_display_name", how="left")

draft_board = draft_board.with_columns([
    (pl.col("seasons_active") * 17).alias("possible_games"),
])

draft_board = draft_board.with_columns([
    (pl.col("possible_games") - pl.col("career_games_played")).alias("career_games_missed")
])

draft_board.select([
    "player_display_name", "position", "seasons_active", "possible_games", "career_games_played", "career_games_missed"
]).sort("career_games_missed", descending=True).head(10)

shape: (10, 6)
┌─────────────────┬──────────┬────────────────┬────────────────┬─────────────────┬─────────────────┐
│ player_display_ ┆ position ┆ seasons_active ┆ possible_games ┆ career_games_pl ┆ career_games_mi │
│ name            ┆ ---      ┆ ---            ┆ ---            ┆ ayed            ┆ ssed            │
│ ---             ┆ str      ┆ u32            ┆ u32            ┆ ---             ┆ ---             │
│ str             ┆          ┆                ┆                ┆ u32             ┆ u32             │
╞═════════════════╪══════════╪════════════════╪════════════════╪═════════════════╪═════════════════╡
│ Jarrett Stidham ┆ QB       ┆ 3              ┆ 51             ┆ 5               ┆ 46              │
│ Gary Brightwell ┆ RB       ┆ 3              ┆ 51             ┆ 7               ┆ 44              │
│ Carson Wentz    ┆ QB       ┆ 3              ┆ 51             ┆ 8               ┆ 43              │
│ Kyle Allen      ┆ QB       ┆ 3              ┆ 51             ┆ 9               ┆ 42              │
│ Robbie Chosen   ┆ WR       ┆ 3              ┆ 51             ┆ 10              ┆ 41              │
│ Ross Dwelley    ┆ TE       ┆ 3              ┆ 51             ┆ 10              ┆ 41              │
│ Jakob Johnson   ┆ RB       ┆ 3              ┆ 51             ┆ 11              ┆ 40              │
│ Jordan Mims     ┆ RB       ┆ 3              ┆ 51             ┆ 11              ┆ 40              │
│ Jimmy Garoppolo ┆ QB       ┆ 3              ┆ 51             ┆ 11              ┆ 40              │
│ Tyson Bagent    ┆ QB       ┆ 3              ┆ 51             ┆ 11              ┆ 40              │
└─────────────────┴──────────┴────────────────┴────────────────┴─────────────────┴─────────────────┘

In [ ]:
draft_board.filter(pl.col("player_display_name") == "Christian McCaffrey").select([
    "player_display_name", "position", "seasons_active", "possible_games", "career_games_played", "career_games_missed", "vorp"
])

shape: (1, 7)
┌───────────────┬──────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────────┐
│ player_displa ┆ position ┆ seasons_acti ┆ possible_gam ┆ career_games ┆ career_games ┆ vorp      │
│ y_name        ┆ ---      ┆ ve           ┆ es           ┆ _played      ┆ _missed      ┆ ---       │
│ ---           ┆ str      ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ f64       │
│ str           ┆          ┆ u32          ┆ u32          ┆ u32          ┆ u32          ┆           │
╞═══════════════╪══════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════════╡
│ Christian     ┆ RB       ┆ 3            ┆ 51           ┆ 37           ┆ 14           ┆ 17.269473 │
│ McCaffrey     ┆          ┆              ┆              ┆              ┆              ┆           │
└───────────────┴──────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────────┘

In [ ]:
draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "seasons_active", "possible_games", "career_games_played", "career_games_missed",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).write_csv("fantasy_draft_board_complete.csv")

In [ ]:
draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "seasons_active", "possible_games", "career_games_played", "career_games_missed",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).write_csv("MY_FANTASY_BOARD_FINAL.csv")

In [ ]:
top_30_overall = draft_board.with_columns([
    (
        pl.col("vorp") - (0.05 * pl.col("career_games_missed"))
    ).alias("final_score")
]).sort("final_score", descending=True).head(30)

top_30_overall.select([
    "player_display_name", "position", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed",
    "vorp", "final_score"
])

NameError: name 'draft_board' is not defined

In [ ]:
import nflreadpy as nfl
import polars as pl

# pull data
data = nfl.load_player_stats([2023, 2024, 2025])

# clean to fantasy positions, regular season only
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week", "season_type",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "targets", "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]
fantasy_data = data.select(fantasy_cols)
fantasy_data = fantasy_data.filter(
    (fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])) &
    (fantasy_data["season_type"] == "REG")
)

# season totals
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("week").n_unique().alias("games_played"),
    pl.col("completions").sum(),
    pl.col("attempts").sum(),
    pl.col("passing_yards").sum(),
    pl.col("passing_tds").sum(),
    pl.col("passing_interceptions").sum(),
    pl.col("carries").sum(),
    pl.col("rushing_yards").sum(),
    pl.col("rushing_tds").sum(),
    pl.col("targets").sum(),
    pl.col("receptions").sum(),
    pl.col("receiving_yards").sum(),
    pl.col("receiving_tds").sum(),
    pl.col("fantasy_points").sum(),
    pl.col("fantasy_points_ppr").sum(),
])

season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

# consistency
consistency = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("fantasy_points_ppr").std().alias("ppr_std_dev"),
])
season_totals = season_totals.join(consistency, on=["player_display_name", "position", "team", "season"])

# target share
team_targets = fantasy_data.group_by(["team", "season"]).agg([
    pl.col("targets").sum().alias("team_total_targets"),
])
season_totals = season_totals.join(team_targets, on=["team", "season"])
season_totals = season_totals.with_columns([
    (pl.col("targets") / pl.col("team_total_targets") * 100).alias("target_share_pct"),
])

# trend (2024 -> 2025)
trend_table = season_totals.pivot(
    values="ppr_per_game", index=["player_display_name", "position"], on="season", aggregate_function="sum"
)
trend_table = trend_table.with_columns([
    (pl.col("2025") - pl.col("2024")).alias("ppr_change_24_to_25")
])
established_trends = trend_table.filter((pl.col("2024") > 5) & (pl.col("2025") > 5))

# career stats
career_stats = season_totals.group_by("player_display_name").agg([
    pl.col("ppr_per_game").mean().alias("career_avg_ppr"),
    pl.col("games_played").sum().alias("career_games_played"),
])
seasons_active = season_totals.group_by("player_display_name").agg([
    pl.col("season").n_unique().alias("seasons_active")
])

# build draft board
draft_board = season_totals.filter(pl.col("season") == 2025).select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception"
])

draft_board = draft_board.join(
    established_trends.select(["player_display_name", "ppr_change_24_to_25"]),
    on="player_display_name", how="left"
)
draft_board = draft_board.join(career_stats, on="player_display_name", how="left")
draft_board = draft_board.join(seasons_active, on="player_display_name", how="left")

draft_board = draft_board.with_columns([
    (pl.col("seasons_active") * 17).alias("possible_games"),
])
draft_board = draft_board.with_columns([
    (pl.col("possible_games") - pl.col("career_games_played")).alias("career_games_missed_2023_2025")
])

# composite score
draft_board = draft_board.with_columns([
    pl.col("ppr_change_24_to_25").fill_null(0).alias("ppr_change_filled")
])
draft_board = draft_board.with_columns([
    (
        pl.col("ppr_per_game")
        - (0.3 * pl.col("ppr_std_dev").fill_null(0))
        + (0.3 * pl.col("ppr_change_filled"))
    ).alias("composite_score")
])

# position rank + tiers
draft_board = draft_board.with_columns([
    pl.col("composite_score").rank(method="ordinal", descending=True).over("position").alias("position_rank")
])
draft_board = draft_board.with_columns([
    pl.when(pl.col("position_rank") <= 3).then(1)
    .when(pl.col("position_rank") <= 8).then(2)
    .when(pl.col("position_rank") <= 15).then(3)
    .when(pl.col("position_rank") <= 24).then(4)
    .otherwise(5)
    .alias("tier")
])

# VORP
replacement_levels = {}
for pos, cutoff in [("QB", 20), ("RB", 31), ("WR", 31), ("TE", 14)]:
    player_at_cutoff = draft_board.filter(
        (pl.col("position") == pos) & (pl.col("position_rank") == cutoff)
    )
    replacement_levels[pos] = player_at_cutoff["composite_score"][0]

draft_board = draft_board.with_columns([
    pl.when(pl.col("position") == "QB").then(pl.col("composite_score") - replacement_levels["QB"])
    .when(pl.col("position") == "RB").then(pl.col("composite_score") - replacement_levels["RB"])
    .when(pl.col("position") == "WR").then(pl.col("composite_score") - replacement_levels["WR"])
    .when(pl.col("position") == "TE").then(pl.col("composite_score") - replacement_levels["TE"])
    .alias("vorp")
])

draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "seasons_active", "possible_games", "career_games_played",
    "career_games_missed_2023_2025",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).head(15)

ModuleNotFoundError: No module named 'nflreadpy'

In [ ]:
!pip install nflreadpy

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.32.4)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (1.35.2)
Requirement already satisfied: platformdirs>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.10.0)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.67.3)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.13.4)
Collecting pydantic-settings>=2.0.0 (from nflreadpy)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->nflreadpy) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2026.6.17)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.3 MB/s eta 0:00:00
Installing collected packages: pydantic-settings, nflreadpy
Successfully installed nflreadpy-0.1.5 pydantic-settings-2.14.2

In [ ]:
import nflreadpy as nfl
import polars as pl

# pull data
data = nfl.load_player_stats([2023, 2024, 2025])

# clean to fantasy positions, regular season only
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week", "season_type",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "targets", "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]
fantasy_data = data.select(fantasy_cols)
fantasy_data = fantasy_data.filter(
    (fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])) &
    (fantasy_data["season_type"] == "REG")
)

# season totals
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("week").n_unique().alias("games_played"),
    pl.col("completions").sum(),
    pl.col("attempts").sum(),
    pl.col("passing_yards").sum(),
    pl.col("passing_tds").sum(),
    pl.col("passing_interceptions").sum(),
    pl.col("carries").sum(),
    pl.col("rushing_yards").sum(),
    pl.col("rushing_tds").sum(),
    pl.col("targets").sum(),
    pl.col("receptions").sum(),
    pl.col("receiving_yards").sum(),
    pl.col("receiving_tds").sum(),
    pl.col("fantasy_points").sum(),
    pl.col("fantasy_points_ppr").sum(),
])

season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

# consistency
consistency = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("fantasy_points_ppr").std().alias("ppr_std_dev"),
])
season_totals = season_totals.join(consistency, on=["player_display_name", "position", "team", "season"])

# target share
team_targets = fantasy_data.group_by(["team", "season"]).agg([
    pl.col("targets").sum().alias("team_total_targets"),
])
season_totals = season_totals.join(team_targets, on=["team", "season"])
season_totals = season_totals.with_columns([
    (pl.col("targets") / pl.col("team_total_targets") * 100).alias("target_share_pct"),
])

# trend (2024 -> 2025)
trend_table = season_totals.pivot(
    values="ppr_per_game", index=["player_display_name", "position"], on="season", aggregate_function="sum"
)
trend_table = trend_table.with_columns([
    (pl.col("2025") - pl.col("2024")).alias("ppr_change_24_to_25")
])
established_trends = trend_table.filter((pl.col("2024") > 5) & (pl.col("2025") > 5))

# career stats
career_stats = season_totals.group_by("player_display_name").agg([
    pl.col("ppr_per_game").mean().alias("career_avg_ppr"),
    pl.col("games_played").sum().alias("career_games_played"),
])
seasons_active = season_totals.group_by("player_display_name").agg([
    pl.col("season").n_unique().alias("seasons_active")
])

# build draft board
draft_board = season_totals.filter(pl.col("season") == 2025).select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception"
])

draft_board = draft_board.join(
    established_trends.select(["player_display_name", "ppr_change_24_to_25"]),
    on="player_display_name", how="left"
)
draft_board = draft_board.join(career_stats, on="player_display_name", how="left")
draft_board = draft_board.join(seasons_active, on="player_display_name", how="left")

draft_board = draft_board.with_columns([
    (pl.col("seasons_active") * 17).alias("possible_games"),
])
draft_board = draft_board.with_columns([
    (pl.col("possible_games") - pl.col("career_games_played")).alias("career_games_missed_2023_2025")
])

# composite score
draft_board = draft_board.with_columns([
    pl.col("ppr_change_24_to_25").fill_null(0).alias("ppr_change_filled")
])
draft_board = draft_board.with_columns([
    (
        pl.col("ppr_per_game")
        - (0.3 * pl.col("ppr_std_dev").fill_null(0))
        + (0.3 * pl.col("ppr_change_filled"))
    ).alias("composite_score")
])

# position rank + tiers
draft_board = draft_board.with_columns([
    pl.col("composite_score").rank(method="ordinal", descending=True).over("position").alias("position_rank")
])
draft_board = draft_board.with_columns([
    pl.when(pl.col("position_rank") <= 3).then(1)
    .when(pl.col("position_rank") <= 8).then(2)
    .when(pl.col("position_rank") <= 15).then(3)
    .when(pl.col("position_rank") <= 24).then(4)
    .otherwise(5)
    .alias("tier")
])

# VORP
replacement_levels = {}
for pos, cutoff in [("QB", 20), ("RB", 31), ("WR", 31), ("TE", 14)]:
    player_at_cutoff = draft_board.filter(
        (pl.col("position") == pos) & (pl.col("position_rank") == cutoff)
    )
    replacement_levels[pos] = player_at_cutoff["composite_score"][0]

draft_board = draft_board.with_columns([
    pl.when(pl.col("position") == "QB").then(pl.col("composite_score") - replacement_levels["QB"])
    .when(pl.col("position") == "RB").then(pl.col("composite_score") - replacement_levels["RB"])
    .when(pl.col("position") == "WR").then(pl.col("composite_score") - replacement_levels["WR"])
    .when(pl.col("position") == "TE").then(pl.col("composite_score") - replacement_levels["TE"])
    .alias("vorp")
])

draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "seasons_active", "possible_games", "career_games_played",
    "career_games_missed_2023_2025",
    "composite_score", "position_rank", "tier", "vorp"
]).sort(["position", "position_rank"]).head(15)

shape: (15, 19)
┌──────────────┬──────────┬──────┬──────────────┬───┬──────────────┬─────────────┬──────┬──────────┐
│ player_displ ┆ position ┆ team ┆ games_played ┆ … ┆ composite_sc ┆ position_ra ┆ tier ┆ vorp     │
│ ay_name      ┆ ---      ┆ ---  ┆ ---          ┆   ┆ ore          ┆ nk          ┆ ---  ┆ ---      │
│ ---          ┆ str      ┆ str  ┆ u32          ┆   ┆ ---          ┆ ---         ┆ i32  ┆ f64      │
│ str          ┆          ┆      ┆              ┆   ┆ f64          ┆ u32         ┆      ┆          │
╞══════════════╪══════════╪══════╪══════════════╪═══╪══════════════╪═════════════╪══════╪══════════╡
│ Drake Maye   ┆ QB       ┆ NE   ┆ 17           ┆ … ┆ 21.210246    ┆ 1           ┆ 1    ┆ 8.175281 │
│ Matthew      ┆ QB       ┆ LA   ┆ 17           ┆ … ┆ 20.676557    ┆ 2           ┆ 1    ┆ 7.641593 │
│ Stafford     ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Josh Allen   ┆ QB       ┆ BUF  ┆ 16           ┆ … ┆ 19.396892    ┆ 3           ┆ 1    ┆ 6.361928 │
│ Trevor       ┆ QB       ┆ JAX  ┆ 17           ┆ … ┆ 18.869171    ┆ 4           ┆ 2    ┆ 5.834207 │
│ Lawrence     ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Patrick      ┆ QB       ┆ KC   ┆ 14           ┆ … ┆ 18.822123    ┆ 5           ┆ 2    ┆ 5.787159 │
│ Mahomes      ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ …            ┆ …        ┆ …    ┆ …            ┆ … ┆ …            ┆ …           ┆ …    ┆ …        │
│ Justin       ┆ QB       ┆ LAC  ┆ 16           ┆ … ┆ 15.950278    ┆ 11          ┆ 3    ┆ 2.915314 │
│ Herbert      ┆          ┆      ┆              ┆   ┆              ┆             ┆      ┆          │
│ Jalen Hurts  ┆ QB       ┆ PHI  ┆ 16           ┆ … ┆ 15.883814    ┆ 12          ┆ 3    ┆ 2.848849 │
│ Bo Nix       ┆ QB       ┆ DEN  ┆ 17           ┆ … ┆ 15.202651    ┆ 13          ┆ 3    ┆ 2.167686 │
│ Jared Goff   ┆ QB       ┆ DET  ┆ 17           ┆ … ┆ 14.735195    ┆ 14          ┆ 3    ┆ 1.700231 │
│ Kyler Murray ┆ QB       ┆ ARI  ┆ 5            ┆ … ┆ 14.443668    ┆ 15          ┆ 3    ┆ 1.408704 │
└──────────────┴──────────┴──────┴──────────────┴───┴──────────────┴─────────────┴──────┴──────────┘

In [ ]:
top_20_qbs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "QB").sort("final_score", descending=True).head(20)

top_20_qbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
])

shape: (20, 10)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ career_avg ┆ career_gam ┆ vorp     ┆ final_sco │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ _ppr       ┆ es_missed_ ┆ ---      ┆ re        │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ 2023_2025  ┆ f64      ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ ---        ┆          ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆          ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ Drake Maye ┆ NE   ┆ 20.703529  ┆ 5.388322   ┆ … ┆ 17.164842  ┆ 4          ┆ 8.175281 ┆ 7.975281  │
│ Matthew    ┆ LA   ┆ 20.610588  ┆ 6.979442   ┆ … ┆ 16.742835  ┆ 3          ┆ 7.641593 ┆ 7.491593  │
│ Stafford   ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Josh Allen ┆ BUF  ┆ 22.78875   ┆ 10.404942  ┆ … ┆ 23.19174   ┆ 2          ┆ 6.361928 ┆ 6.261928  │
│ Patrick    ┆ KC   ┆ 20.405714  ┆ 7.9956     ┆ … ┆ 18.536071  ┆ 5          ┆ 5.787159 ┆ 5.537159  │
│ Mahomes    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Trevor     ┆ JAX  ┆ 19.892941  ┆ 8.785508   ┆ … ┆ 16.940564  ┆ 8          ┆ 5.834207 ┆ 5.434207  │
│ Lawrence   ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
│ Kyler      ┆ ARI  ┆ 15.556     ┆ 1.779067   ┆ … ┆ 17.111902  ┆ 21         ┆ 1.408704 ┆ 0.358704  │
│ Murray     ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Jordan     ┆ GB   ┆ 15.676     ┆ 7.40908    ┆ … ┆ 16.678301  ┆ 4          ┆ 0.443912 ┆ 0.243912  │
│ Love       ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ C.J.       ┆ HOU  ┆ 14.895714  ┆ 6.520945   ┆ … ┆ 15.420192  ┆ 5          ┆ 0.484122 ┆ 0.234122  │
│ Stroud     ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Justin     ┆ NYJ  ┆ 15.851111  ┆ 10.795402  ┆ … ┆ 15.157088  ┆ 19         ┆ 0.75866  ┆ -0.19134  │
│ Fields     ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Jayden     ┆ WAS  ┆ 16.325714  ┆ 6.364293   ┆ … ┆ 18.628151  ┆ 10         ┆ 0.0      ┆ -0.5      │
│ Daniels    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘

In [ ]:
top_20_rbs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "RB").sort("final_score", descending=True).head(20)

top_20_rbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
])

shape: (20, 10)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ career_avg ┆ career_ga ┆ vorp      ┆ final_sco │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ _ppr       ┆ mes_misse ┆ ---       ┆ re        │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ d_2023_20 ┆ f64       ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ 25        ┆           ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ ---       ┆           ┆           │
│            ┆      ┆            ┆            ┆   ┆            ┆ u32       ┆           ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Christian  ┆ SF   ┆ 24.505882  ┆ 8.224466   ┆ … ┆ 20.304044  ┆ 14        ┆ 17.269473 ┆ 16.569473 │
│ McCaffrey  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bijan      ┆ ATL  ┆ 21.811765  ┆ 10.258404  ┆ … ┆ 18.8       ┆ 0         ┆ 10.711938 ┆ 10.711938 │
│ Robinson   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ De'Von     ┆ MIA  ┆ 20.175     ┆ 7.015364   ┆ … ┆ 18.38418   ┆ 7         ┆ 10.294703 ┆ 9.944703  │
│ Achane     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jonathan   ┆ IND  ┆ 21.311765  ┆ 12.441507  ┆ … ┆ 18.143445  ┆ 10        ┆ 10.193436 ┆ 9.693436  │
│ Taylor     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jahmyr     ┆ DET  ┆ 21.582353  ┆ 13.527206  ┆ … ┆ 19.689804  ┆ 2         ┆ 9.058945  ┆ 8.958945  │
│ Gibbs      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Omarion    ┆ LAC  ┆ 15.077778  ┆ 8.075082   ┆ … ┆ 15.077778  ┆ 8         ┆ 4.119419  ┆ 3.719419  │
│ Hampton    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Ashton     ┆ LV   ┆ 14.417647  ┆ 8.685277   ┆ … ┆ 14.417647  ┆ 0         ┆ 3.276229  ┆ 3.276229  │
│ Jeanty     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bucky      ┆ TB   ┆ 13.85      ┆ 5.608179   ┆ … ┆ 14.113235  ┆ 7         ┆ 3.473771  ┆ 3.123771  │
│ Irving     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Kenny      ┆ PIT  ┆ 13.017647  ┆ 9.377915   ┆ … ┆ 7.595417   ┆ 1         ┆ 1.668438  ┆ 1.618438  │
│ Gainwell   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Phil Mafah ┆ DAL  ┆ 10.9       ┆ null       ┆ … ┆ 10.9       ┆ 16        ┆ 2.364166  ┆ 1.564166  │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
top_20_wrs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "WR").sort("final_score", descending=True).head(20)

top_20_wrs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
])

shape: (20, 10)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ career_avg ┆ career_ga ┆ vorp      ┆ final_sco │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ _ppr       ┆ mes_misse ┆ ---       ┆ re        │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ d_2023_20 ┆ f64       ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ 25        ┆           ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ ---       ┆           ┆           │
│            ┆      ┆            ┆            ┆   ┆            ┆ u32       ┆           ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Puka Nacua ┆ LA   ┆ 23.4375    ┆ 10.208812  ┆ … ┆ 19.926047  ┆ 7         ┆ 11.721781 ┆ 11.371781 │
│ Jaxon Smit ┆ SEA  ┆ 21.170588  ┆ 7.481207   ┆ … ┆ 14.954902  ┆ 0         ┆ 10.762917 ┆ 10.762917 │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Chris      ┆ NO   ┆ 16.75      ┆ 7.914291   ┆ … ┆ 13.597917  ┆ 11        ┆ 6.474683  ┆ 5.924683  │
│ Olave      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Rashee     ┆ KC   ┆ 18.7625    ┆ 8.111533   ┆ … ┆ 16.089583  ┆ 23        ┆ 7.04051   ┆ 5.89051   │
│ Rice       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Amon-Ra    ┆ DET  ┆ 19.058824  ┆ 10.929207  ┆ … ┆ 19.446299  ┆ 1         ┆ 5.868281  ┆ 5.818281  │
│ St. Brown  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Michael    ┆ ARI  ┆ 12.976471  ┆ 10.60292   ┆ … ┆ 9.855138   ┆ 5         ┆ 1.304381  ┆ 1.054381  │
│ Wilson     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Quentin    ┆ LAC  ┆ 13.169231  ┆ 7.442937   ┆ … ┆ 10.115103  ┆ 6         ┆ 1.343339  ┆ 1.043339  │
│ Johnston   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ A.J. Brown ┆ PHI  ┆ 14.686667  ┆ 9.751547   ┆ … ┆ 16.135525  ┆ 6         ┆ 1.112038  ┆ 0.812038  │
│ Rashid     ┆ NO   ┆ 11.6       ┆ 4.691215   ┆ … ┆ 10.385     ┆ 12        ┆ 1.272855  ┆ 0.672855  │
│ Shaheed    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Garrett    ┆ NYJ  ┆ 14.214286  ┆ 9.657713   ┆ … ┆ 13.857703  ┆ 10        ┆ 1.086183  ┆ 0.586183  │
│ Wilson     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
top_10_tes = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "TE").sort("final_score", descending=True).head(10)

top_10_tes.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
])

shape: (10, 10)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ career_avg ┆ career_gam ┆ vorp     ┆ final_sco │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ _ppr       ┆ es_missed_ ┆ ---      ┆ re        │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ 2023_2025  ┆ f64      ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ ---        ┆          ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆          ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ Trey       ┆ ARI  ┆ 18.582353  ┆ 8.366468   ┆ … ┆ 14.832108  ┆ 1          ┆ 7.709811 ┆ 7.659811  │
│ McBride    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Tucker     ┆ GB   ┆ 14.65      ┆ 9.870447   ┆ … ┆ 9.954342   ┆ 12         ┆ 3.836044 ┆ 3.236044  │
│ Kraft      ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ George     ┆ SF   ┆ 14.681818  ┆ 8.260244   ┆ … ┆ 14.385051  ┆ 9          ┆ 2.510233 ┆ 2.060233  │
│ Kittle     ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Brock      ┆ LV   ┆ 14.683333  ┆ 10.123675  ┆ … ┆ 15.068137  ┆ 5          ┆ 2.049292 ┆ 1.799292  │
│ Bowers     ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Kyle Pitts ┆ ATL  ┆ 12.4       ┆ 9.940636   ┆ … ┆ 9.398039   ┆ 0          ┆ 1.456458 ┆ 1.456458  │
│ Dallas     ┆ PHI  ┆ 12.34      ┆ 7.17414    ┆ … ┆ 10.811905  ┆ 12         ┆ 1.415701 ┆ 0.815701  │
│ Goedert    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Harold     ┆ CLE  ┆ 11.65      ┆ 5.729107   ┆ … ┆ 11.65      ┆ 1          ┆ 0.565211 ┆ 0.515211  │
│ Fannin Jr. ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Jake       ┆ DAL  ┆ 11.064706  ┆ 7.089424   ┆ … ┆ 9.646499   ┆ 3          ┆ 0.654091 ┆ 0.504091  │
│ Ferguson   ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Sam        ┆ DET  ┆ 11.877778  ┆ 6.454219   ┆ … ┆ 12.288916  ┆ 9          ┆ 0.865039 ┆ 0.415039  │
│ LaPorta    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Dalton     ┆ HOU  ┆ 10.452941  ┆ 5.639162   ┆ … ┆ 9.146405   ┆ 2          ┆ 0.445136 ┆ 0.345136  │
│ Schultz    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘

In [ ]:
top_20_qbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
]).write_csv("top_20_QB.csv")

top_20_rbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
]).write_csv("top_20_RB.csv")

top_20_wrs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
]).write_csv("top_20_WR.csv")

top_10_tes.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
]).write_csv("top_10_TE.csv")

NameError: name 'top_20_qbs' is not defined

In [ ]:
!pip install nflreadpy

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.32.4)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (1.35.2)
Requirement already satisfied: platformdirs>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.10.0)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.67.3)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.13.4)
Collecting pydantic-settings>=2.0.0 (from nflreadpy)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->nflreadpy) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2026.6.17)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.4 MB/s eta 0:00:00
Installing collected packages: pydantic-settings, nflreadpy
Successfully installed nflreadpy-0.1.5 pydantic-settings-2.14.2

In [ ]:
import nflreadpy as nfl
import polars as pl

# pull data
data = nfl.load_player_stats([2023, 2024, 2025])

# clean to fantasy positions, regular season only
fantasy_cols = [
    "player_display_name", "position", "team", "season", "week", "season_type",
    "completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions",
    "carries", "rushing_yards", "rushing_tds",
    "targets", "receptions", "receiving_yards", "receiving_tds",
    "fantasy_points", "fantasy_points_ppr"
]
fantasy_data = data.select(fantasy_cols)
fantasy_data = fantasy_data.filter(
    (fantasy_data["position"].is_in(["QB", "RB", "WR", "TE"])) &
    (fantasy_data["season_type"] == "REG")
)

# season totals
season_totals = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("week").n_unique().alias("games_played"),
    pl.col("completions").sum(),
    pl.col("attempts").sum(),
    pl.col("passing_yards").sum(),
    pl.col("passing_tds").sum(),
    pl.col("passing_interceptions").sum(),
    pl.col("carries").sum(),
    pl.col("rushing_yards").sum(),
    pl.col("rushing_tds").sum(),
    pl.col("targets").sum(),
    pl.col("receptions").sum(),
    pl.col("receiving_yards").sum(),
    pl.col("receiving_tds").sum(),
    pl.col("fantasy_points").sum(),
    pl.col("fantasy_points_ppr").sum(),
])

season_totals = season_totals.with_columns([
    (pl.col("fantasy_points_ppr") / pl.col("games_played")).alias("ppr_per_game"),
    (pl.col("rushing_yards") / pl.col("carries")).alias("yards_per_carry"),
    (pl.col("receiving_yards") / pl.col("receptions")).alias("yards_per_reception"),
])

# consistency
consistency = fantasy_data.group_by(["player_display_name", "position", "team", "season"]).agg([
    pl.col("fantasy_points_ppr").std().alias("ppr_std_dev"),
])
season_totals = season_totals.join(consistency, on=["player_display_name", "position", "team", "season"])

# target share
team_targets = fantasy_data.group_by(["team", "season"]).agg([
    pl.col("targets").sum().alias("team_total_targets"),
])
season_totals = season_totals.join(team_targets, on=["team", "season"])
season_totals = season_totals.with_columns([
    (pl.col("targets") / pl.col("team_total_targets") * 100).alias("target_share_pct"),
])

# trend (2024 -> 2025)
trend_table = season_totals.pivot(
    values="ppr_per_game", index=["player_display_name", "position"], on="season", aggregate_function="sum"
)
trend_table = trend_table.with_columns([
    (pl.col("2025") - pl.col("2024")).alias("ppr_change_24_to_25")
])
established_trends = trend_table.filter((pl.col("2024") > 5) & (pl.col("2025") > 5))

# career stats
career_stats = season_totals.group_by("player_display_name").agg([
    pl.col("ppr_per_game").mean().alias("career_avg_ppr"),
    pl.col("games_played").sum().alias("career_games_played"),
])
seasons_active = season_totals.group_by("player_display_name").agg([
    pl.col("season").n_unique().alias("seasons_active")
])

# build draft board
draft_board = season_totals.filter(pl.col("season") == 2025).select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception"
])

draft_board = draft_board.join(
    established_trends.select(["player_display_name", "ppr_change_24_to_25"]),
    on="player_display_name", how="left"
)
draft_board = draft_board.join(career_stats, on="player_display_name", how="left")
draft_board = draft_board.join(seasons_active, on="player_display_name", how="left")

draft_board = draft_board.with_columns([
    (pl.col("seasons_active") * 17).alias("possible_games"),
])
draft_board = draft_board.with_columns([
    (pl.col("possible_games") - pl.col("career_games_played")).alias("career_games_missed_2023_2025")
])

# composite score
draft_board = draft_board.with_columns([
    pl.col("ppr_change_24_to_25").fill_null(0).alias("ppr_change_filled")
])
draft_board = draft_board.with_columns([
    (
        pl.col("ppr_per_game")
        - (0.3 * pl.col("ppr_std_dev").fill_null(0))
        + (0.3 * pl.col("ppr_change_filled"))
    ).alias("composite_score")
])

# position rank + tiers
draft_board = draft_board.with_columns([
    pl.col("composite_score").rank(method="ordinal", descending=True).over("position").alias("position_rank")
])
draft_board = draft_board.with_columns([
    pl.when(pl.col("position_rank") <= 3).then(1)
    .when(pl.col("position_rank") <= 8).then(2)
    .when(pl.col("position_rank") <= 15).then(3)
    .when(pl.col("position_rank") <= 24).then(4)
    .otherwise(5)
    .alias("tier")
])

# VORP
replacement_levels = {}
for pos, cutoff in [("QB", 20), ("RB", 31), ("WR", 31), ("TE", 14)]:
    player_at_cutoff = draft_board.filter(
        (pl.col("position") == pos) & (pl.col("position_rank") == cutoff)
    )
    replacement_levels[pos] = player_at_cutoff["composite_score"][0]

draft_board = draft_board.with_columns([
    pl.when(pl.col("position") == "QB").then(pl.col("composite_score") - replacement_levels["QB"])
    .when(pl.col("position") == "RB").then(pl.col("composite_score") - replacement_levels["RB"])
    .when(pl.col("position") == "WR").then(pl.col("composite_score") - replacement_levels["WR"])
    .when(pl.col("position") == "TE").then(pl.col("composite_score") - replacement_levels["TE"])
    .alias("vorp")
])

draft_board.head()

shape: (5, 20)
┌──────────────┬──────────┬──────┬──────────────┬───┬─────────────┬─────────────┬──────┬───────────┐
│ player_displ ┆ position ┆ team ┆ games_played ┆ … ┆ composite_s ┆ position_ra ┆ tier ┆ vorp      │
│ ay_name      ┆ ---      ┆ ---  ┆ ---          ┆   ┆ core        ┆ nk          ┆ ---  ┆ ---       │
│ ---          ┆ str      ┆ str  ┆ u32          ┆   ┆ ---         ┆ ---         ┆ i32  ┆ f64       │
│ str          ┆          ┆      ┆              ┆   ┆ f64         ┆ u32         ┆      ┆           │
╞══════════════╪══════════╪══════╪══════════════╪═══╪═════════════╪═════════════╪══════╪═══════════╡
│ Tyquan       ┆ WR       ┆ KC   ┆ 12           ┆ … ┆ 5.02162     ┆ 75          ┆ 5    ┆ -5.02816  │
│ Thornton     ┆          ┆      ┆              ┆   ┆             ┆             ┆      ┆           │
│ Kyle         ┆ RB       ┆ CHI  ┆ 17           ┆ … ┆ 6.74553     ┆ 38          ┆ 5    ┆ -1.790305 │
│ Monangai     ┆          ┆      ┆              ┆   ┆             ┆             ┆      ┆           │
│ Alex Bachman ┆ WR       ┆ LV   ┆ 11           ┆ … ┆ 0.092612    ┆ 223         ┆ 5    ┆ -9.957168 │
│ Jalen Nailor ┆ WR       ┆ MIN  ┆ 17           ┆ … ┆ 3.60391     ┆ 102         ┆ 5    ┆ -6.44587  │
│ Troy         ┆ WR       ┆ DEN  ┆ 17           ┆ … ┆ 8.130055    ┆ 45          ┆ 5    ┆ -1.919725 │
│ Franklin     ┆          ┆      ┆              ┆   ┆             ┆             ┆      ┆           │
└──────────────┴──────────┴──────┴──────────────┴───┴─────────────┴─────────────┴──────┴───────────┘

In [ ]:
top_20_qbs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "QB").sort("final_score", descending=True).head(20)

top_20_rbs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "RB").sort("final_score", descending=True).head(20)

top_20_wrs = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "WR").sort("final_score", descending=True).head(20)

top_10_tes = draft_board.with_columns([
    (pl.col("vorp") - (0.05 * pl.col("career_games_missed_2023_2025"))).alias("final_score")
]).filter(pl.col("position") == "TE").sort("final_score", descending=True).head(10)

cols = [
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev",
    "target_share_pct", "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "final_score"
]

top_20_qbs.select(cols).write_csv("top_20_QB.csv")
top_20_rbs.select(cols).write_csv("top_20_RB.csv")
top_20_wrs.select(cols).write_csv("top_20_WR.csv")
top_10_tes.select(cols).write_csv("top_10_TE.csv")

top_20_qbs.select(cols).head(5)

shape: (5, 10)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ career_avg ┆ career_gam ┆ vorp     ┆ final_sco │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ _ppr       ┆ es_missed_ ┆ ---      ┆ re        │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ 2023_2025  ┆ f64      ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ ---        ┆          ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆          ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ Drake Maye ┆ NE   ┆ 20.703529  ┆ 5.388322   ┆ … ┆ 17.164842  ┆ 4          ┆ 8.175281 ┆ 7.975281  │
│ Matthew    ┆ LA   ┆ 20.610588  ┆ 6.979442   ┆ … ┆ 16.742835  ┆ 3          ┆ 7.641593 ┆ 7.491593  │
│ Stafford   ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Josh Allen ┆ BUF  ┆ 22.78875   ┆ 10.404942  ┆ … ┆ 23.19174   ┆ 2          ┆ 6.361928 ┆ 6.261928  │
│ Patrick    ┆ KC   ┆ 20.405714  ┆ 7.9956     ┆ … ┆ 18.536071  ┆ 5          ┆ 5.787159 ┆ 5.537159  │
│ Mahomes    ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ Trevor     ┆ JAX  ┆ 19.892941  ┆ 8.785508   ┆ … ┆ 16.940564  ┆ 8          ┆ 5.834207 ┆ 5.434207  │
│ Lawrence   ┆      ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘

In [ ]:
team_stats = nfl.load_team_stats(seasons=[2023, 2024, 2025])
team_stats.columns

['season',
 'week',
 'team',
 'season_type',
 'game_id',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'timeouts',
 'fumbles_forced_by_opp',
 'fumbles_not_forced',
 'fumbles_out_of_bounds',
 'fumbles_total',
 'fumbles_lost_total',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pt_att',
 'pt_blocked',
 'pt_long',
 'pt_yards',
 'pt_inside_20',
 'pt_out_of_bounds',
 'pt_downed',
 'pt_touchback',
 'pt_fair_caught',
 'pt_returned',
 'pt_return_yards',
 'pt_return_tds',
 'pt_net_yards']

In [ ]:
team_proxies = team_stats.filter(pl.col("season_type") == "REG").group_by(["team", "season"]).agg([
    pl.col("sacks_suffered").sum().alias("season_sacks_suffered"),
    pl.col("sack_yards_lost").sum().alias("season_sack_yards_lost"),
    pl.col("rushing_epa").mean().alias("avg_rushing_epa"),
    pl.col("passing_epa").mean().alias("avg_passing_epa"),
    pl.col("attempts").sum().alias("season_pass_attempts"),
    pl.col("carries").sum().alias("season_carries"),
])

team_proxies = team_proxies.with_columns([
    (pl.col("season_pass_attempts") / (pl.col("season_pass_attempts") + pl.col("season_carries")) * 100).alias("pass_rate_pct")
])

team_proxies.head()

shape: (5, 9)
┌──────┬────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ team ┆ season ┆ season_sack ┆ season_sac ┆ … ┆ avg_passin ┆ season_pas ┆ season_car ┆ pass_rate_ │
│ ---  ┆ ---    ┆ s_suffered  ┆ k_yards_lo ┆   ┆ g_epa      ┆ s_attempts ┆ ries       ┆ pct        │
│ str  ┆ i32    ┆ ---         ┆ st         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│      ┆        ┆ i32         ┆ ---        ┆   ┆ f64        ┆ i32        ┆ i32        ┆ f64        │
│      ┆        ┆             ┆ i32        ┆   ┆            ┆            ┆            ┆            │
╞══════╪════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ CHI  ┆ 2023   ┆ 50          ┆ -325       ┆ … ┆ -3.802921  ┆ 513        ┆ 534        ┆ 48.997135  │
│ CLE  ┆ 2023   ┆ 45          ┆ -318       ┆ … ┆ -6.173754  ┆ 624        ┆ 518        ┆ 54.640981  │
│ DEN  ┆ 2023   ┆ 52          ┆ -304       ┆ … ┆ -0.595516  ┆ 513        ┆ 451        ┆ 53.215768  │
│ DET  ┆ 2023   ┆ 31          ┆ -205       ┆ … ┆ 4.888864   ┆ 606        ┆ 500        ┆ 54.792043  │
│ GB   ┆ 2023   ┆ 30          ┆ -242       ┆ … ┆ 5.300558   ┆ 581        ┆ 441        ┆ 56.849315  │
└──────┴────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
draft_board = draft_board.join(
    team_proxies.filter(pl.col("season") == 2025).select([
        "team", "season_sacks_suffered", "avg_rushing_epa", "avg_passing_epa", "pass_rate_pct"
    ]),
    on="team", how="left"
)

draft_board.select([
    "player_display_name", "position", "team", "ppr_per_game", "vorp",
    "season_sacks_suffered", "avg_rushing_epa", "avg_passing_epa", "pass_rate_pct"
]).head(10)

shape: (10, 9)
┌────────────┬──────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_dis ┆ position ┆ team ┆ ppr_per_ga ┆ … ┆ season_sac ┆ avg_rushin ┆ avg_passin ┆ pass_rate │
│ play_name  ┆ ---      ┆ ---  ┆ me         ┆   ┆ ks_suffere ┆ g_epa      ┆ g_epa      ┆ _pct      │
│ ---        ┆ str      ┆ str  ┆ ---        ┆   ┆ d          ┆ ---        ┆ ---        ┆ ---       │
│ str        ┆          ┆      ┆ f64        ┆   ┆ ---        ┆ f64        ┆ f64        ┆ f64       │
│            ┆          ┆      ┆            ┆   ┆ i32        ┆            ┆            ┆           │
╞════════════╪══════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Tyquan     ┆ WR       ┆ KC   ┆ 6.733333   ┆ … ┆ 47         ┆ 0.498256   ┆ 1.463744   ┆ 57.593688 │
│ Thornton   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Kyle       ┆ RB       ┆ CHI  ┆ 8.629412   ┆ … ┆ 24         ┆ 1.938881   ┆ 2.817526   ┆ 53.197405 │
│ Monangai   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Alex       ┆ WR       ┆ LV   ┆ 0.290909   ┆ … ┆ 64         ┆ -5.696472  ┆ -6.327811  ┆ 58.257919 │
│ Bachman    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Jalen      ┆ WR       ┆ MIN  ┆ 5.923529   ┆ … ┆ 60         ┆ -0.763852  ┆ -5.945268  ┆ 54.138702 │
│ Nailor     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Troy       ┆ WR       ┆ DEN  ┆ 10.417647  ┆ … ┆ 23         ┆ -0.54739   ┆ 3.460731   ┆ 57.343312 │
│ Franklin   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Terry      ┆ WR       ┆ WAS  ┆ 11.42      ┆ … ┆ 37         ┆ 0.277485   ┆ -0.37694   ┆ 49.213012 │
│ McLaurin   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Julius     ┆ RB       ┆ TEN  ┆ 0.25       ┆ … ┆ 56         ┆ -1.477229  ┆ -7.830714  ┆ 60.126582 │
│ Chestnut   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Dominic    ┆ WR       ┆ DET  ┆ 0.0        ┆ … ┆ 39         ┆ -1.445209  ┆ 6.080001   ┆ 56.835938 │
│ Lovett     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Gary       ┆ RB       ┆ CIN  ┆ 0.0        ┆ … ┆ 36         ┆ 0.412315   ┆ 0.785171   ┆ 62.683643 │
│ Brightwell ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Hassan     ┆ RB       ┆ LAC  ┆ 0.909091   ┆ … ┆ 60         ┆ -0.37133   ┆ -1.373652  ┆ 54.975845 │
│ Haskins    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
rosters = nfl.load_rosters(seasons=[2025, 2026])
rosters.columns

['season',
 'team',
 'position',
 'depth_chart_position',
 'jersey_number',
 'status',
 'full_name',
 'first_name',
 'last_name',
 'birth_date',
 'height',
 'weight',
 'college',
 'gsis_id',
 'espn_id',
 'sportradar_id',
 'yahoo_id',
 'rotowire_id',
 'pff_id',
 'pfr_id',
 'fantasy_data_id',
 'sleeper_id',
 'years_exp',
 'headshot_url',
 'ngs_position',
 'week',
 'game_type',
 'status_description_abbr',
 'football_name',
 'esb_id',
 'gsis_it_id',
 'smart_id',
 'entry_year',
 'rookie_year',
 'draft_club',
 'draft_number']

In [ ]:
rosters.filter(pl.col("season") == 2026).select(["team", "position", "full_name"]).head(10)

shape: (10, 3)
┌──────┬──────────┬──────────────────┐
│ team ┆ position ┆ full_name        │
│ ---  ┆ ---      ┆ ---              │
│ str  ┆ str      ┆ str              │
╞══════╪══════════╪══════════════════╡
│ PIT  ┆ QB       ┆ Aaron Rodgers    │
│ ATL  ┆ K        ┆ Nick Folk        │
│ CAR  ┆ LS       ┆ J.J. Jansen      │
│ CIN  ┆ QB       ┆ Joe Flacco       │
│ BAL  ┆ DL       ┆ Calais Campbell  │
│ CIN  ┆ QB       ┆ Josh Johnson     │
│ LA   ┆ QB       ┆ Matthew Stafford │
│ SF   ┆ LS       ┆ Jon Weeks        │
│ TEN  ┆ LS       ┆ Morgan Cox       │
│ SF   ┆ OL       ┆ Trent Williams   │
└──────┴──────────┴──────────────────┘

In [ ]:
roster_2025 = rosters.filter(pl.col("season") == 2025).select(["team", "full_name", "position"]).unique()
roster_2026 = rosters.filter(pl.col("season") == 2026).select(["team", "full_name", "position"]).unique()

new_additions = roster_2026.join(roster_2025, on=["team", "full_name"], how="anti")

new_additions.filter(pl.col("position").is_in(["QB", "RB", "WR", "TE"])).head(15)

shape: (15, 3)
┌──────┬───────────────────┬──────────┐
│ team ┆ full_name         ┆ position │
│ ---  ┆ ---               ┆ ---      │
│ str  ┆ str               ┆ str      │
╞══════╪═══════════════════╪══════════╡
│ TB   ┆ Bauer Sharp       ┆ TE       │
│ ATL  ┆ Tyler Goodson     ┆ RB       │
│ MIA  ┆ Carlos Washington ┆ RB       │
│ MIA  ┆ Cole Turner       ┆ TE       │
│ DAL  ┆ Tyler Johnson     ┆ WR       │
│ …    ┆ …                 ┆ …        │
│ HOU  ┆ Foster Moreau     ┆ TE       │
│ GB   ┆ Brenden Rice      ┆ WR       │
│ CHI  ┆ Omari Kelly       ┆ WR       │
│ TB   ┆ Jalon Daniels     ┆ QB       │
│ CIN  ┆ Colbie Young      ┆ WR       │
└──────┴───────────────────┴──────────┘

In [ ]:
new_competition_count = new_additions.filter(pl.col("position").is_in(["QB", "RB", "WR", "TE"])).group_by(["team", "position"]).agg([
    pl.len().alias("new_players_at_position")
])

new_competition_count.sort("new_players_at_position", descending=True).head(15)

shape: (15, 3)
┌──────┬──────────┬─────────────────────────┐
│ team ┆ position ┆ new_players_at_position │
│ ---  ┆ ---      ┆ ---                     │
│ str  ┆ str      ┆ u32                     │
╞══════╪══════════╪═════════════════════════╡
│ LV   ┆ WR       ┆ 8                       │
│ MIA  ┆ WR       ┆ 8                       │
│ MIN  ┆ WR       ┆ 8                       │
│ DAL  ┆ WR       ┆ 7                       │
│ JAX  ┆ WR       ┆ 7                       │
│ …    ┆ …        ┆ …                       │
│ WAS  ┆ WR       ┆ 6                       │
│ CHI  ┆ WR       ┆ 6                       │
│ DEN  ┆ WR       ┆ 6                       │
│ KC   ┆ WR       ┆ 6                       │
│ NYG  ┆ WR       ┆ 6                       │
└──────┴──────────┴─────────────────────────┘

In [ ]:
drafted_additions = new_additions.join(
    rosters.filter(pl.col("season") == 2026).select(["team", "full_name", "draft_number"]).unique(),
    on=["team", "full_name"], how="left"
)

drafted_rookies = drafted_additions.filter(
    (pl.col("position").is_in(["QB", "RB", "WR", "TE"])) &
    (pl.col("draft_number").is_not_null())
)

drafted_rookies.select(["team", "full_name", "position", "draft_number"]).sort("draft_number").head(15)

shape: (15, 4)
┌──────┬───────────────────┬──────────┬──────────────┐
│ team ┆ full_name         ┆ position ┆ draft_number │
│ ---  ┆ ---               ┆ ---      ┆ ---          │
│ str  ┆ str               ┆ str      ┆ i32          │
╞══════╪═══════════════════╪══════════╪══════════════╡
│ MIN  ┆ Kyler Murray      ┆ QB       ┆ 1            │
│ LV   ┆ Fernando Mendoza  ┆ QB       ┆ 1            │
│ TEN  ┆ Mitchell Trubisky ┆ QB       ┆ 2            │
│ NO   ┆ Zach Wilson       ┆ QB       ┆ 2            │
│ ARI  ┆ Jeremiyah Love    ┆ RB       ┆ 3            │
│ …    ┆ …                 ┆ …        ┆ …            │
│ KC   ┆ Justin Fields     ┆ QB       ┆ 11           │
│ NYG  ┆ Odell Beckham Jr. ┆ WR       ┆ 12           │
│ LA   ┆ Ty Simpson        ┆ QB       ┆ 13           │
│ ATL  ┆ Jahan Dotson      ┆ WR       ┆ 16           │
│ NYJ  ┆ Kenyon Sadiq      ┆ TE       ┆ 16           │
└──────┴───────────────────┴──────────┴──────────────┘

In [ ]:
true_rookies = new_additions.join(
    rosters.filter(pl.col("season") == 2026).select(["team", "full_name", "draft_number", "rookie_year"]).unique(),
    on=["team", "full_name"], how="left"
)

true_rookies = true_rookies.filter(
    (pl.col("position").is_in(["QB", "RB", "WR", "TE"])) &
    (pl.col("rookie_year") == 2026)
)

true_rookies.select(["team", "full_name", "position", "draft_number"]).sort("draft_number").head(15)

shape: (15, 4)
┌──────┬─────────────────┬──────────┬──────────────┐
│ team ┆ full_name       ┆ position ┆ draft_number │
│ ---  ┆ ---             ┆ ---      ┆ ---          │
│ str  ┆ str             ┆ str      ┆ i32          │
╞══════╪═════════════════╪══════════╪══════════════╡
│ ARI  ┆ Jameson Geers   ┆ TE       ┆ null         │
│ TB   ┆ Eric Rivers     ┆ WR       ┆ null         │
│ CHI  ┆ Omari Kelly     ┆ WR       ┆ null         │
│ TB   ┆ Jalon Daniels   ┆ QB       ┆ null         │
│ SEA  ┆ Lance Mason     ┆ TE       ┆ null         │
│ …    ┆ …               ┆ …        ┆ …            │
│ ATL  ┆ Cash Jones      ┆ RB       ┆ null         │
│ DAL  ┆ Romello Brinson ┆ WR       ┆ null         │
│ BAL  ┆ Dontae McMillan ┆ RB       ┆ null         │
│ DET  ┆ Luke Altmyer    ┆ QB       ┆ null         │
│ DET  ┆ Miles Kitselman ┆ TE       ┆ null         │
└──────┴─────────────────┴──────────┴──────────────┘

In [ ]:
true_rookies.select(["team", "full_name", "position", "draft_number"]).sort("draft_number", nulls_last=True).head(15)

shape: (15, 4)
┌──────┬────────────────────┬──────────┬──────────────┐
│ team ┆ full_name          ┆ position ┆ draft_number │
│ ---  ┆ ---                ┆ ---      ┆ ---          │
│ str  ┆ str                ┆ str      ┆ i32          │
╞══════╪════════════════════╪══════════╪══════════════╡
│ LV   ┆ Fernando Mendoza   ┆ QB       ┆ 1            │
│ ARI  ┆ Jeremiyah Love     ┆ RB       ┆ 3            │
│ TEN  ┆ Carnell Tate       ┆ WR       ┆ 4            │
│ NO   ┆ Jordyn Tyson       ┆ WR       ┆ 8            │
│ LA   ┆ Ty Simpson         ┆ QB       ┆ 13           │
│ …    ┆ …                  ┆ …        ┆ …            │
│ SF   ┆ De'Zhaun Stribling ┆ WR       ┆ 33           │
│ CLE  ┆ Denzel Boston      ┆ WR       ┆ 39           │
│ PIT  ┆ Germie Bernard     ┆ WR       ┆ 47           │
│ PHI  ┆ Eli Stowers        ┆ TE       ┆ 54           │
│ JAX  ┆ Nate Boerkircher   ┆ TE       ┆ 56           │
└──────┴────────────────────┴──────────┴──────────────┘

In [ ]:
schedules = nfl.load_schedules(seasons=[2025, 2026])
schedules.select(["season", "week", "home_team", "home_coach", "away_team", "away_coach"]).head(10)

shape: (10, 6)
┌────────┬──────┬───────────┬─────────────────┬───────────┬──────────────────────┐
│ season ┆ week ┆ home_team ┆ home_coach      ┆ away_team ┆ away_coach           │
│ ---    ┆ ---  ┆ ---       ┆ ---             ┆ ---       ┆ ---                  │
│ i32    ┆ i32  ┆ str       ┆ str             ┆ str       ┆ str                  │
╞════════╪══════╪═══════════╪═════════════════╪═══════════╪══════════════════════╡
│ 2025   ┆ 1    ┆ PHI       ┆ Nick Sirianni   ┆ DAL       ┆ Brian Schottenheimer │
│ 2025   ┆ 1    ┆ LAC       ┆ Jim Harbaugh    ┆ KC        ┆ Andy Reid            │
│ 2025   ┆ 1    ┆ ATL       ┆ Raheem Morris   ┆ TB        ┆ Todd Bowles          │
│ 2025   ┆ 1    ┆ CLE       ┆ Kevin Stefanski ┆ CIN       ┆ Zac Taylor           │
│ 2025   ┆ 1    ┆ IND       ┆ Shane Steichen  ┆ MIA       ┆ Mike McDaniel        │
│ 2025   ┆ 1    ┆ JAX       ┆ Liam Coen       ┆ CAR       ┆ Dave Canales         │
│ 2025   ┆ 1    ┆ NE        ┆ Mike Vrabel     ┆ LV        ┆ Pete Carroll         │
│ 2025   ┆ 1    ┆ NO        ┆ Kellen Moore    ┆ ARI       ┆ Jonathan Gannon      │
│ 2025   ┆ 1    ┆ NYJ       ┆ Aaron Glenn     ┆ PIT       ┆ Mike Tomlin          │
│ 2025   ┆ 1    ┆ WAS       ┆ Dan Quinn       ┆ NYG       ┆ Brian Daboll         │
└────────┴──────┴───────────┴─────────────────┴───────────┴──────────────────────┘

In [ ]:
schedules.filter(pl.col("season") == 2026).select(["season", "week", "home_team", "home_coach"]).head(10)

shape: (10, 4)
┌────────┬──────┬───────────┬────────────────┐
│ season ┆ week ┆ home_team ┆ home_coach     │
│ ---    ┆ ---  ┆ ---       ┆ ---            │
│ i32    ┆ i32  ┆ str       ┆ str            │
╞════════╪══════╪═══════════╪════════════════╡
│ 2026   ┆ 1    ┆ SEA       ┆ Mike Macdonald │
│ 2026   ┆ 1    ┆ LA        ┆ Sean McVay     │
│ 2026   ┆ 1    ┆ CAR       ┆ Dave Canales   │
│ 2026   ┆ 1    ┆ CIN       ┆ Zac Taylor     │
│ 2026   ┆ 1    ┆ DET       ┆ Dan Campbell   │
│ 2026   ┆ 1    ┆ HOU       ┆ DeMeco Ryans   │
│ 2026   ┆ 1    ┆ IND       ┆ Shane Steichen │
│ 2026   ┆ 1    ┆ JAX       ┆ Liam Coen      │
│ 2026   ┆ 1    ┆ PIT       ┆ Mike McCarthy  │
│ 2026   ┆ 1    ┆ TEN       ┆ Robert Saleh   │
└────────┴──────┴───────────┴────────────────┘

In [ ]:
coach_2025 = schedules.filter(pl.col("season") == 2025).select(["home_team", "home_coach"]).unique().rename({"home_team": "team", "home_coach": "coach_2025"})
coach_2026 = schedules.filter(pl.col("season") == 2026).select(["home_team", "home_coach"]).unique().rename({"home_team": "team", "home_coach": "coach_2026"})

coach_comparison = coach_2025.join(coach_2026, on="team", how="inner")

coach_comparison = coach_comparison.with_columns([
    (pl.col("coach_2025") != pl.col("coach_2026")).alias("new_head_coach")
])

coach_comparison.sort("new_head_coach", descending=True)

shape: (32, 4)
┌──────┬─────────────────┬───────────────┬────────────────┐
│ team ┆ coach_2025      ┆ coach_2026    ┆ new_head_coach │
│ ---  ┆ ---             ┆ ---           ┆ ---            │
│ str  ┆ str             ┆ str           ┆ bool           │
╞══════╪═════════════════╪═══════════════╪════════════════╡
│ MIA  ┆ Mike McDaniel   ┆ Jeff Hafley   ┆ true           │
│ PIT  ┆ Mike Tomlin     ┆ Mike McCarthy ┆ true           │
│ LV   ┆ Pete Carroll    ┆ Klint Kubliak ┆ true           │
│ CLE  ┆ Kevin Stefanski ┆ Todd Monken   ┆ true           │
│ TEN  ┆ Brian Callahan  ┆ Robert Saleh  ┆ true           │
│ …    ┆ …               ┆ …             ┆ …              │
│ CHI  ┆ Ben Johnson     ┆ Ben Johnson   ┆ false          │
│ LA   ┆ Sean McVay      ┆ Sean McVay    ┆ false          │
│ NO   ┆ Kellen Moore    ┆ Kellen Moore  ┆ false          │
│ HOU  ┆ DeMeco Ryans    ┆ DeMeco Ryans  ┆ false          │
│ LAC  ┆ Jim Harbaugh    ┆ Jim Harbaugh  ┆ false          │
└──────┴─────────────────┴───────────────┴────────────────┘

In [ ]:
draft_board = draft_board.join(
    coach_comparison.select(["team", "new_head_coach"]),
    on="team", how="left"
)

draft_board.select([
    "player_display_name", "position", "team", "ppr_per_game", "vorp", "new_head_coach"
]).filter(pl.col("new_head_coach") == True).head(15)

shape: (15, 6)
┌─────────────────────┬──────────┬──────┬──────────────┬───────────┬────────────────┐
│ player_display_name ┆ position ┆ team ┆ ppr_per_game ┆ vorp      ┆ new_head_coach │
│ ---                 ┆ ---      ┆ ---  ┆ ---          ┆ ---       ┆ ---            │
│ str                 ┆ str      ┆ str  ┆ f64          ┆ f64       ┆ bool           │
╞═════════════════════╪══════════╪══════╪══════════════╪═══════════╪════════════════╡
│ Alex Bachman        ┆ WR       ┆ LV   ┆ 0.290909     ┆ -9.957168 ┆ true           │
│ Julius Chestnut     ┆ RB       ┆ TEN  ┆ 0.25         ┆ -8.479329 ┆ true           │
│ Carter Runyon       ┆ TE       ┆ LV   ┆ 0.433333     ┆ -9.15789  ┆ true           │
│ Jakobi Meyers       ┆ WR       ┆ LV   ┆ 9.742857     ┆ 0.60508   ┆ true           │
│ Ray-Ray McCloud     ┆ WR       ┆ NYG  ┆ 0.75         ┆ -9.617978 ┆ true           │
│ …                   ┆ …        ┆ …    ┆ …            ┆ …         ┆ …              │
│ Lamar Jackson       ┆ QB       ┆ BAL  ┆ 16.527692    ┆ -1.869082 ┆ true           │
│ Joe Flacco          ┆ QB       ┆ CLE  ┆ 6.475        ┆ -6.316619 ┆ true           │
│ Rashod Bateman      ┆ WR       ┆ BAL  ┆ 4.261538     ┆ -7.220541 ┆ true           │
│ Blake Whiteheart    ┆ TE       ┆ CLE  ┆ 0.266667     ┆ -9.260945 ┆ true           │
│ Lil'Jordan Humphrey ┆ WR       ┆ NYG  ┆ 4.75         ┆ -7.315034 ┆ true           │
└─────────────────────┴──────────┴──────┴──────────────┴───────────┴────────────────┘

In [ ]:
rookie_competition = drafted_rookies.group_by(["team", "position"]).agg([
    pl.len().alias("new_rookies_at_position")
])

draft_board = draft_board.join(
    rookie_competition,
    on=["team", "position"], how="left"
).with_columns([
    pl.col("new_rookies_at_position").fill_null(0)
])

draft_board.select([
    "player_display_name", "position", "team", "ppr_per_game", "vorp",
    "season_sacks_suffered", "avg_rushing_epa", "avg_passing_epa", "pass_rate_pct",
    "new_head_coach", "new_rookies_at_position"
]).head(10)

shape: (10, 11)
┌────────────┬──────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_dis ┆ position ┆ team ┆ ppr_per_ga ┆ … ┆ avg_passin ┆ pass_rate_ ┆ new_head_c ┆ new_rooki │
│ play_name  ┆ ---      ┆ ---  ┆ me         ┆   ┆ g_epa      ┆ pct        ┆ oach       ┆ es_at_pos │
│ ---        ┆ str      ┆ str  ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ition     │
│ str        ┆          ┆      ┆ f64        ┆   ┆ f64        ┆ f64        ┆ bool       ┆ ---       │
│            ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆ u32       │
╞════════════╪══════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Tyquan     ┆ WR       ┆ KC   ┆ 6.733333   ┆ … ┆ 1.463744   ┆ 57.593688  ┆ false      ┆ 1         │
│ Thornton   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Kyle       ┆ RB       ┆ CHI  ┆ 8.629412   ┆ … ┆ 2.817526   ┆ 53.197405  ┆ false      ┆ 0         │
│ Monangai   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Alex       ┆ WR       ┆ LV   ┆ 0.290909   ┆ … ┆ -6.327811  ┆ 58.257919  ┆ true       ┆ 3         │
│ Bachman    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Jalen      ┆ WR       ┆ MIN  ┆ 5.923529   ┆ … ┆ -5.945268  ┆ 54.138702  ┆ false      ┆ 1         │
│ Nailor     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Troy       ┆ WR       ┆ DEN  ┆ 10.417647  ┆ … ┆ 3.460731   ┆ 57.343312  ┆ false      ┆ 2         │
│ Franklin   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Terry      ┆ WR       ┆ WAS  ┆ 11.42      ┆ … ┆ -0.37694   ┆ 49.213012  ┆ false      ┆ 3         │
│ McLaurin   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Julius     ┆ RB       ┆ TEN  ┆ 0.25       ┆ … ┆ -7.830714  ┆ 60.126582  ┆ true       ┆ 2         │
│ Chestnut   ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Dominic    ┆ WR       ┆ DET  ┆ 0.0        ┆ … ┆ 6.080001   ┆ 56.835938  ┆ false      ┆ 2         │
│ Lovett     ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Gary       ┆ RB       ┆ CIN  ┆ 0.0        ┆ … ┆ 0.785171   ┆ 62.683643  ┆ false      ┆ 0         │
│ Brightwell ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
│ Hassan     ┆ RB       ┆ LAC  ┆ 0.909091   ┆ … ┆ -1.373652  ┆ 54.975845  ┆ false      ┆ 0         │
│ Haskins    ┆          ┆      ┆            ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
draft_board.select([
    "player_display_name", "position", "team", "games_played",
    "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "yards_per_carry", "yards_per_reception", "ppr_change_24_to_25",
    "career_avg_ppr", "seasons_active", "possible_games", "career_games_played",
    "career_games_missed_2023_2025",
    "composite_score", "position_rank", "tier", "vorp",
    "season_sacks_suffered", "avg_rushing_epa", "avg_passing_epa", "pass_rate_pct",
    "new_head_coach", "new_rookies_at_position"
]).sort(["position", "position_rank"]).write_csv("COMPLETE_FINAL_DRAFT_BOARD.csv")

In [ ]:
draft_board = draft_board.with_columns([
    pl.when(pl.col("position") == "RB").then(pl.col("avg_rushing_epa"))
    .otherwise(pl.col("avg_passing_epa"))
    .alias("relevant_team_epa")
])

draft_board.select(["player_display_name", "position", "avg_rushing_epa", "avg_passing_epa", "relevant_team_epa"]).head(10)

shape: (10, 5)
┌─────────────────────┬──────────┬─────────────────┬─────────────────┬───────────────────┐
│ player_display_name ┆ position ┆ avg_rushing_epa ┆ avg_passing_epa ┆ relevant_team_epa │
│ ---                 ┆ ---      ┆ ---             ┆ ---             ┆ ---               │
│ str                 ┆ str      ┆ f64             ┆ f64             ┆ f64               │
╞═════════════════════╪══════════╪═════════════════╪═════════════════╪═══════════════════╡
│ Tyquan Thornton     ┆ WR       ┆ 0.498256        ┆ 1.463744        ┆ 1.463744          │
│ Kyle Monangai       ┆ RB       ┆ 1.938881        ┆ 2.817526        ┆ 1.938881          │
│ Alex Bachman        ┆ WR       ┆ -5.696472       ┆ -6.327811       ┆ -6.327811         │
│ Jalen Nailor        ┆ WR       ┆ -0.763852       ┆ -5.945268       ┆ -5.945268         │
│ Troy Franklin       ┆ WR       ┆ -0.54739        ┆ 3.460731        ┆ 3.460731          │
│ Terry McLaurin      ┆ WR       ┆ 0.277485        ┆ -0.37694        ┆ -0.37694          │
│ Julius Chestnut     ┆ RB       ┆ -1.477229       ┆ -7.830714       ┆ -1.477229         │
│ Dominic Lovett      ┆ WR       ┆ -1.445209       ┆ 6.080001        ┆ 6.080001          │
│ Gary Brightwell     ┆ RB       ┆ 0.412315        ┆ 0.785171        ┆ 0.412315          │
│ Hassan Haskins      ┆ RB       ┆ -0.37133        ┆ -1.373652       ┆ -0.37133          │
└─────────────────────┴──────────┴─────────────────┴─────────────────┴───────────────────┘

In [ ]:
draft_board = draft_board.with_columns([
    (
        pl.col("vorp")
        - (0.05 * pl.col("career_games_missed_2023_2025"))
        + (0.2 * pl.col("relevant_team_epa"))
        - pl.when(pl.col("new_head_coach") == True).then(1.0).otherwise(0.0)
        - (0.3 * pl.col("new_rookies_at_position"))
    ).alias("everything_score")
])

draft_board.select([
    "player_display_name", "position", "vorp", "relevant_team_epa",
    "new_head_coach", "new_rookies_at_position", "everything_score"
]).sort("everything_score", descending=True).head(10)

shape: (10, 7)
┌───────────────┬──────────┬───────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ player_displa ┆ position ┆ vorp      ┆ relevant_tea ┆ new_head_coa ┆ new_rookies_ ┆ everything_s │
│ y_name        ┆ ---      ┆ ---       ┆ m_epa        ┆ ch           ┆ at_position  ┆ core         │
│ ---           ┆ str      ┆ f64       ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│ str           ┆          ┆           ┆ f64          ┆ bool         ┆ u32          ┆ f64          │
╞═══════════════╪══════════╪═══════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ Christian     ┆ RB       ┆ 17.269473 ┆ -1.087205    ┆ false        ┆ 1            ┆ 16.052032    │
│ McCaffrey     ┆          ┆           ┆              ┆              ┆              ┆              │
│ Puka Nacua    ┆ WR       ┆ 11.721781 ┆ 8.850253     ┆ false        ┆ 1            ┆ 12.841832    │
│ Jaxon         ┆ WR       ┆ 10.762917 ┆ 4.018505     ┆ false        ┆ 1            ┆ 11.266618    │
│ Smith-Njigba  ┆          ┆           ┆              ┆              ┆              ┆              │
│ Bijan         ┆ RB       ┆ 10.711938 ┆ -1.12961     ┆ false        ┆ 1            ┆ 10.186017    │
│ Robinson      ┆          ┆           ┆              ┆              ┆              ┆              │
│ Jonathan      ┆ RB       ┆ 10.193436 ┆ 1.999472     ┆ false        ┆ 1            ┆ 9.79333      │
│ Taylor        ┆          ┆           ┆              ┆              ┆              ┆              │
│ Drake Maye    ┆ QB       ┆ 8.175281  ┆ 9.565112     ┆ false        ┆ 1            ┆ 9.588304     │
│ Matthew       ┆ QB       ┆ 7.641593  ┆ 8.850253     ┆ false        ┆ 1            ┆ 8.961644     │
│ Stafford      ┆          ┆           ┆              ┆              ┆              ┆              │
│ De'Von Achane ┆ RB       ┆ 10.294703 ┆ -0.728294    ┆ true         ┆ 0            ┆ 8.799045     │
│ Jahmyr Gibbs  ┆ RB       ┆ 9.058945  ┆ -1.445209    ┆ false        ┆ 1            ┆ 8.369903     │
│ Trey McBride  ┆ TE       ┆ 7.709811  ┆ 0.279975     ┆ false        ┆ 1            ┆ 7.415806     │
└───────────────┴──────────┴───────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [ ]:
final_qbs = draft_board.filter(pl.col("position") == "QB").sort("everything_score", descending=True)

final_qbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "relevant_team_epa", "new_head_coach", "new_rookies_at_position", "everything_score"
])

shape: (82, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ relevant_t ┆ new_head_ ┆ new_rooki ┆ everythin │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ eam_epa    ┆ coach     ┆ es_at_pos ┆ g_score   │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ition     ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ bool      ┆ ---       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆ u32       ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Drake Maye ┆ NE   ┆ 20.703529  ┆ 5.388322   ┆ … ┆ 9.565112   ┆ false     ┆ 1         ┆ 9.588304  │
│ Matthew    ┆ LA   ┆ 20.610588  ┆ 6.979442   ┆ … ┆ 8.850253   ┆ false     ┆ 1         ┆ 8.961644  │
│ Stafford   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Josh Allen ┆ BUF  ┆ 22.78875   ┆ 10.404942  ┆ … ┆ 5.70946    ┆ false     ┆ 0         ┆ 7.40382   │
│ Trevor     ┆ JAX  ┆ 19.892941  ┆ 8.785508   ┆ … ┆ 2.42997    ┆ false     ┆ 0         ┆ 5.920201  │
│ Lawrence   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Patrick    ┆ KC   ┆ 20.405714  ┆ 7.9956     ┆ … ┆ 1.463744   ┆ false     ┆ 2         ┆ 5.229908  │
│ Mahomes    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Max        ┆ MIN  ┆ 0.602857   ┆ 2.03887    ┆ … ┆ -5.945268  ┆ false     ┆ 1         ┆ -15.03282 │
│ Brosmer    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 2         │
│ Zach       ┆ MIA  ┆ 0.345      ┆ 0.828714   ┆ … ┆ 0.28999    ┆ true      ┆ 1         ┆ -15.08058 │
│ Wilson     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Cooper     ┆ BAL  ┆ 0.43       ┆ 1.45451    ┆ … ┆ 0.265307   ┆ true      ┆ 1         ┆ -15.68825 │
│ Rush       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Brandon    ┆ TEN  ┆ 0.88       ┆ null       ┆ … ┆ -7.830714  ┆ true      ┆ 2         ┆ -16.82110 │
│ Allen      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 7         │
│ Kenny      ┆ LV   ┆ 1.286667   ┆ 3.681232   ┆ … ┆ -6.327811  ┆ true      ┆ 2         ┆ -17.11822 │
│ Pickett    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 9         │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
final_rbs = draft_board.filter(pl.col("position") == "RB").sort("everything_score", descending=True)

final_rbs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "relevant_team_epa", "new_head_coach", "new_rookies_at_position", "everything_score"
])

shape: (158, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ relevant_t ┆ new_head_ ┆ new_rooki ┆ everythin │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ eam_epa    ┆ coach     ┆ es_at_pos ┆ g_score   │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ition     ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ bool      ┆ ---       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆ u32       ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Christian  ┆ SF   ┆ 24.505882  ┆ 8.224466   ┆ … ┆ -1.087205  ┆ false     ┆ 1         ┆ 16.052032 │
│ McCaffrey  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bijan      ┆ ATL  ┆ 21.811765  ┆ 10.258404  ┆ … ┆ -1.12961   ┆ false     ┆ 1         ┆ 10.186017 │
│ Robinson   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jonathan   ┆ IND  ┆ 21.311765  ┆ 12.441507  ┆ … ┆ 1.999472   ┆ false     ┆ 1         ┆ 9.79333   │
│ Taylor     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ De'Von     ┆ MIA  ┆ 20.175     ┆ 7.015364   ┆ … ┆ -0.728294  ┆ true      ┆ 0         ┆ 8.799045  │
│ Achane     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jahmyr     ┆ DET  ┆ 21.582353  ┆ 13.527206  ┆ … ┆ -1.445209  ┆ false     ┆ 1         ┆ 8.369903  │
│ Gibbs      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Trey       ┆ PIT  ┆ 0.0        ┆ 0.0        ┆ … ┆ 0.212104   ┆ true      ┆ 2         ┆ -11.34341 │
│ Sermon     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 4         │
│ Dylan      ┆ LV   ┆ 0.335294   ┆ 0.933368   ┆ … ┆ -5.696472  ┆ true      ┆ 1         ┆ -11.46984 │
│ Laube      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Julius     ┆ TEN  ┆ 0.25       ┆ 0.644981   ┆ … ┆ -1.477229  ┆ true      ┆ 2         ┆ -11.47477 │
│ Chestnut   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 4         │
│ Jakob      ┆ HOU  ┆ 0.0        ┆ 0.0        ┆ … ┆ -2.643284  ┆ false     ┆ 2         ┆ -11.66449 │
│ Johnson    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 1         │
│ Jordan     ┆ TEN  ┆ 0.0        ┆ null       ┆ … ┆ -1.477229  ┆ true      ┆ 2         ┆ -12.43128 │
│ Mims       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
final_wrs = draft_board.filter(pl.col("position") == "WR").sort("everything_score", descending=True)

final_wrs.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "relevant_team_epa", "new_head_coach", "new_rookies_at_position", "everything_score"
])

shape: (255, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ relevant_t ┆ new_head_ ┆ new_rooki ┆ everythin │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ eam_epa    ┆ coach     ┆ es_at_pos ┆ g_score   │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ition     ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ bool      ┆ ---       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆ u32       ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Puka Nacua ┆ LA   ┆ 23.4375    ┆ 10.208812  ┆ … ┆ 8.850253   ┆ false     ┆ 1         ┆ 12.841832 │
│ Jaxon Smit ┆ SEA  ┆ 21.170588  ┆ 7.481207   ┆ … ┆ 4.018505   ┆ false     ┆ 1         ┆ 11.266618 │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Amon-Ra    ┆ DET  ┆ 19.058824  ┆ 10.929207  ┆ … ┆ 6.080001   ┆ false     ┆ 2         ┆ 6.434281  │
│ St. Brown  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ George     ┆ DAL  ┆ 17.170588  ┆ 9.650632   ┆ … ┆ 6.701969   ┆ false     ┆ 3         ┆ 6.144331  │
│ Pickens    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Rashee     ┆ KC   ┆ 18.7625    ┆ 8.111533   ┆ … ┆ 1.463744   ┆ false     ┆ 1         ┆ 5.883259  │
│ Rice       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Dee        ┆ MIA  ┆ 0.927273   ┆ 1.991025   ┆ … ┆ 0.28999    ┆ true      ┆ 7         ┆ -14.31181 │
│ Eskridge   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 7         │
│ Mason      ┆ TEN  ┆ 1.133333   ┆ 1.86619    ┆ … ┆ -7.830714  ┆ true      ┆ 3         ┆ -14.59244 │
│ Kinsey     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 7         │
│ DeAndre    ┆ CLE  ┆ 0.0        ┆ 0.0        ┆ … ┆ -9.658078  ┆ true      ┆ 3         ┆ -14.73139 │
│ Carter     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ DJ Turner  ┆ LV   ┆ 0.0        ┆ null       ┆ … ┆ -6.327811  ┆ true      ┆ 3         ┆ -14.76534 │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 2         │
│ Kaden      ┆ CLE  ┆ 0.0        ┆ null       ┆ … ┆ -9.658078  ┆ true      ┆ 3         ┆ -15.48139 │
│ Davis      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
final_tes = draft_board.filter(pl.col("position") == "TE").sort("everything_score", descending=True)

final_tes.select([
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "relevant_team_epa", "new_head_coach", "new_rookies_at_position", "everything_score"
])

shape: (138, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ relevant_t ┆ new_head_ ┆ new_rooki ┆ everythin │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ eam_epa    ┆ coach     ┆ es_at_pos ┆ g_score   │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ition     ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ bool      ┆ ---       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆ u32       ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Trey       ┆ ARI  ┆ 18.582353  ┆ 8.366468   ┆ … ┆ 0.279975   ┆ false     ┆ 1         ┆ 7.415806  │
│ McBride    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Tucker     ┆ GB   ┆ 14.65      ┆ 9.870447   ┆ … ┆ 6.988022   ┆ false     ┆ 0         ┆ 4.633649  │
│ Kraft      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ George     ┆ SF   ┆ 14.681818  ┆ 8.260244   ┆ … ┆ 6.296715   ┆ false     ┆ 0         ┆ 3.319577  │
│ Kittle     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jake       ┆ DAL  ┆ 11.064706  ┆ 7.089424   ┆ … ┆ 6.701969   ┆ false     ┆ 0         ┆ 1.844485  │
│ Ferguson   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Sam        ┆ DET  ┆ 11.877778  ┆ 6.454219   ┆ … ┆ 6.080001   ┆ false     ┆ 1         ┆ 1.331039  │
│ LaPorta    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Sal        ┆ CLE  ┆ 1.55       ┆ 2.192031   ┆ … ┆ -9.658078  ┆ true      ┆ 2         ┆ -12.75528 │
│ Cannella   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 2         │
│ David Mart ┆ TEN  ┆ 1.181818   ┆ 2.167403   ┆ … ┆ -7.830714  ┆ true      ┆ 3         ┆ -13.25060 │
│ in-Robinso ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 2         │
│ n          ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Justin     ┆ LV   ┆ 0.0        ┆ 0.0        ┆ … ┆ -6.327811  ┆ true      ┆ 1         ┆ -13.43161 │
│ Shorter    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 9         │
│ Brenden    ┆ CLE  ┆ 1.125      ┆ 1.40327    ┆ … ┆ -9.658078  ┆ true      ┆ 2         ┆ -13.59365 │
│ Bates      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 3         │
│ Blake      ┆ CLE  ┆ 0.266667   ┆ 0.538516   ┆ … ┆ -9.658078  ┆ true      ┆ 2         ┆ -13.69256 │
│ Whiteheart ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 1         │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
cols = [
    "player_display_name", "team", "ppr_per_game", "ppr_std_dev", "target_share_pct",
    "ppr_change_24_to_25", "career_avg_ppr", "career_games_missed_2023_2025",
    "vorp", "relevant_team_epa", "new_head_coach", "new_rookies_at_position", "everything_score"
]

final_qbs.select(cols).write_csv("FINAL_QB_RANKINGS.csv")
final_rbs.select(cols).write_csv("FINAL_RB_RANKINGS.csv")
final_wrs.select(cols).write_csv("FINAL_WR_RANKINGS.csv")
final_tes.select(cols).write_csv("FINAL_TE_RANKINGS.csv")

final_qbs.select(cols).head(5)

shape: (5, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ team ┆ ppr_per_ga ┆ ppr_std_de ┆ … ┆ relevant_t ┆ new_head_ ┆ new_rooki ┆ everythin │
│ play_name  ┆ ---  ┆ me         ┆ v          ┆   ┆ eam_epa    ┆ coach     ┆ es_at_pos ┆ g_score   │
│ ---        ┆ str  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ition     ┆ ---       │
│ str        ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ bool      ┆ ---       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆ u32       ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Drake Maye ┆ NE   ┆ 20.703529  ┆ 5.388322   ┆ … ┆ 9.565112   ┆ false     ┆ 1         ┆ 9.588304  │
│ Matthew    ┆ LA   ┆ 20.610588  ┆ 6.979442   ┆ … ┆ 8.850253   ┆ false     ┆ 1         ┆ 8.961644  │
│ Stafford   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Josh Allen ┆ BUF  ┆ 22.78875   ┆ 10.404942  ┆ … ┆ 5.70946    ┆ false     ┆ 0         ┆ 7.40382   │
│ Trevor     ┆ JAX  ┆ 19.892941  ┆ 8.785508   ┆ … ┆ 2.42997    ┆ false     ┆ 0         ┆ 5.920201  │
│ Lawrence   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Patrick    ┆ KC   ┆ 20.405714  ┆ 7.9956     ┆ … ┆ 1.463744   ┆ false     ┆ 2         ┆ 5.229908  │
│ Mahomes    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘